City-of-Helsinki/berth-reservations

- reservations/api.py
This way, it will not be possible to submit reservations using
Django REST's form at this endpoint.
> Disable browsable API for reservations endpoint

- reservations/signals.py
This way failure while sending notifications does not
fail the entire POST request from the frontend.
> Do not throttle on OSErrors

- reservations/api.py
- reservations/models.py
- reservations/signals.py
- reservations/utils.py
We need to fire a custom signal when all m2m relations are saved.
Otherwise, post_save catches reservations before its HarborChoices
have been created and connected to it.
Notifications should be aware of the reservartion's language.
> Send notification when reservation is fully saved

- reservations/api.py
This way, when API's language is set to Finnish or any other
language, where commas are the standard decimal separator, the
endpoint will accept both dots and commas in decimal fields.
NOTE: if the language is set to languages, where dot is the
standard decimal separator, f.ex. English, then only dots will
be allowed.
> Localize decimal fields for reservations' endpoint

- reservations/api.py
These fields are nullable and blankable on the model, so we can
keep themnon required at the API level.
> Make decimal fields non required at reservations' endpoint

- berth_reservations/settings.py
- notifications/apps.py
- notifications/signals.py
- notifications/tests/conftest.py
- notifications/tests/test_mailer_integration.py
- notifications/tests/test_notifications_render.py
- notifications/utils.py
- requirements.in
- requirements.txt
Anymail recommends using some kind of queueing for
the emails to be sent, as the requests can fail quite easily.
https://anymail.readthedocs.io/en/stable/tips/transient_errors/
The easiest way to do this is django-mailer.
> Switch to django mailer

- notifications/utils.py
We should not fail the interaction with the client, if sending
emails fails for some reason. We catch all errors anyway in
sentry.
> Do not throttle on the mailer errors

- reservations/schema.py
GraphQL's own ID scalar is always a string. Let's be consistent
with it and also use strings for ForeignKey fields in our
mutations.
> Use strings for ID inputs for graphql mutations

- reservations/schema.py
Turns out, GraphQL provides a neat way of handling ID fields
with an ID scalar. This way it will accept both strings and
integers.
> Use ID scalars in GraphQL mutations for ID fields

- reservations/schema.py
Store pier field as blank, when no info given.
> Fix berth reservation mutation for switch applications

- reservations/utils.py
Wider cell fits more text and is more admin-friendly.
> Make current berth cell in excel wider

- berth_reservations/urls.py
- berth_reservations/views.py
By default the graphql errors in django-graphene are silenced.
This makes for a difficult debugging experience, so let's send
them explicitly to sentry whenever possible.
> Send graphql errors to sentry always

- berth_reservations/views.py
If the request has no graphql entities (queries or mutations)
the result is `None` and checking for errors on it leads to
TypeErrors.
> Fix error lookup for graphql calls

- berth_reservations/views.py
Try to send the errors from the graphql response right away.
If the error is not the right type for capture_exception
util, then catch this new error object.
> Improve sentry wrapper for graphql view

- README.md
- reservations/fixtures/switch-reasons.json
- reservations/schema.py
- Make berth switch reasons (relevant for the City of Helsinki)
installable as fixtures.
- Make sure applications cannot be queried at the GraphQL level
as part of the berth switch reasons' queries.
> Switch reasons fixtures

- berth_reservations/tests/utils.py
- resources/schema.py
- resources/tests/test_resources_mutations.py
* Add mutation and tests for the `BerthType` resource.
Partially closes VEN-143
To manually test the mutations, you can run the following queries on GraphiQL with the inputs provided. Just add valid IDs and you're ready to test. :rocket:
```graphql
query FetchBerthTypes {
berthTypes {
edges {
node {
id
width
length
mooringType
}
}
}
}
query	FetchBerthType {
berthType(id: "") {
id
width
length
mooringType
}
}
mutation CreateBerthTypeMutation($input: CreateBerthTypeMutationInput!) {
createBerthType(input: $input) {
berthType {
id
width
length
mooringType
}
}
}
mutation UpdateBerthTypeMutation($updateInput: UpdateBerthTypeMutationInput!){
updateBerthType(input: $updateInput) {
berthType {
id
width
length
mooringType
}
}
}
mutation DeleteBerthType($deleteInput:DeleteBerthTypeMutationInput!) { …
```
> VEN-143 | BerthType mutations

- berth_reservations/views.py
Update the view sending the errors to Sentry to avoid sending "common" errors, as objects not found and other stuff that is not relevant to be logged.
It implements the same code as [Kukkuu](https://github.com/City-of-Helsinki/kukkuu/blob/develop/kukkuu/views.py).
Closes [VEN-389](https://helsinkisolutionoffice.atlassian.net/browse/VEN-389)
If you want to test locally without running Sentry, you can replace [L23](https://github.com/City-of-Helsinki/berth-reservations/pull/117/files#diff-9309524292bdc615bcbca2b085950214R23)
```python
if errors:
self._capture_sentry_exceptions(result.errors, query)
```
for
```python
if errors:
print("🔥🔥🔥🔥 Exception caught 🔥🔥🔥🔥")
```
And add a `raise Exception("message")` in any of the GQL queries/mutations.
> Add error handling for Sentry

- applications/new_schema.py
Since we’re treating harbor as an id, it shouldn’t be a nullable value.
```graphql
type HarborChoiceType {
harbor: String!
priority: Int!
}
```
> Hotfix: Add required to harbor ID on HarborChoiceType

- applications/enums.py
Some of the possible statuses were missing from the enum.
> Add some Application statuses

- applications/new_schema.py
Frontend would like to display the name right away, without
fetching the harbor object. This way FE can build the full link
as is specified by the designs using just one "berthApplications"
query.
> Include harbor name in harbor choices at GQL API

- .github/pull_request_template.md
- applications/schema.py
- berth_reservations/new_schema.py
- berth_reservations/schema.py
- berth_reservations/tests/utils.py
- berth_reservations/urls.py
- customers/schema.py
- leases/schema.py
- leases/tests/conftest.py
- leases/tests/test_lease_queries.py
* Split the "old" and "new" GQL schemas in two sparate files to avoid type conflicts
* Add a custom `AuthorizationNode(graphene.relay.Node)` to secure `Node` queries which require permissions
* Add queries to fetch `Leases`
Close [VEN-348](https://helsinkisolutionoffice.atlassian.net/browse/VEN-348)
To test using `pytest`, run:
```sh
$  pytest leases/tests/test_lease_queries.py
```
To test manually, run the following queries:
```graphql
query GetLeases {
berthLeases {
edges {
node {
id
createdAt
modifiedAt
status
startDate
endDate
comment
boat {
id
name
}
customer {
id
invoicingType
comment
createdAt
modifiedAt
boats {
id
name
}
}
application {
id
customer {
boats {
name
}
}
}
berth {
id
number
berthType {
id
}
}
}
}
}
}
query GetLease {
berthLease(id: "") {
id
application {
id
customer { …
```
> VEN-348 | Expose leases

- customers/schema.py
Since BerthProfileNode implements relay.Node, we should use it to
resolve single nodes too.
> Use Node from relay to resolve BerthProfileNode

- resources/schema.py
This way we ensure that this public types only have the fields
we explicitly marked as available.
> Specify explicitly available fields on berths and winter places

- resources/schema.py
* Add a `servicemapIds` filter to the `harbors` query
* The query takes as filter a string containing a comma serparated list of the desired IDs: `harbors(servicemapIds: ["41234", "41321"]) {}`
* Add a query `harborByServicemapId` to fetch a specific harbor
Closes [VEN-435](https://helsinkisolutionoffice.atlassian.net/browse/VEN-435)
```graphql
query HarborIds {
harbors(servicemapIds: ["41234"]) {
edges {
node {
id
properties {
name
servicemapId
}
}
}
}
}
query Harbor {
harborByServicemapId(servicemapId: "41234") {
id
properties {
name
servicemapId
}
}
}
```
> VEN-435 | servicemap_id filter

- resources/schema.py
BerthType and WinterStoragePlaceType have non-nullable dimensions,
so mark them as required in the schema. Also, this file has fields
after the Meta options of each type, so move these there. At some
point we should decide if fields should come before or after Meta
options and use that across the entire codebase.
> Fix resources' schema

- applications/new_schema.py
- applications/tests/test_applications_new_schema_queries.py
* Add a filter for `BerthApplications` to filter based on whether the application has a customer or not
* Add tests for the filtered query
Close [VEN-484](https://helsinkisolutionoffice.atlassian.net/browse/VEN-484)
```shell
$ pytest applications/tests/test_applications_new_schema_queries.py
```
**Manual testing 👷** 
```graphql
query APPLICATIONS {
berthApplications(noCustomer: true) {
edges {
node {
id
berthSwitch {
reason {
id
}
}
}
}
}
}
```
**No customer= true**
**No customer = false**
> Add NO_CUSTOMER filter to applications and test

- .github/pull_request_template.md
- leases/schema.py
- leases/tests/test_lease_mutations.py
* Add mutation to delete BerthLease and tests
Closes [VEN-483](https://helsinkisolutionoffice.atlassian.net/browse/VEN-483)
```shell
$ pytest leases/tests/test_lease_mutations.py
```
**Manual testing 👷** 
```graphql
mutation DELETE_DRAFTED_APPLICATION($input: DeleteBerthLeaseMutationInput!) {
deleteBerthLease(input: $input) {
__typename
}
}
```
Input:
```json
{
"input": {
"id": ""
}
}
```
As per the [task descripiton](https://helsinkisolutionoffice.atlassian.net/browse/VEN-483):
> MVP solution: only allow deleting if the status is DRAFTED
If the BerthLease receives a lease that has already been moved from `DRAFTED`, it will throw a `VenepaikkaGraphQLError` saying:
```python
raise VenepaikkaGraphQLError(
_(f"Lease object is not DRAFTED anymore: {lease.status}")
)
```
> VEN-483 | Delete drafted BerthLeases

- applications/schema.py
- applications/signals.py
- applications/tests/test_reservations_graphql.py
- applications/tests/test_reservations_notifications.py
* Rename all `Reservation` related stuff to `Application`
Closes [VEN-425](https://helsinkisolutionoffice.atlassian.net/browse/VEN-425)
```shell
$ pyest applications
```
Has to be merged simultaneously with [https://github.com/City-of-Helsinki/berth-reservations-ui/pull/261](https://github.com/City-of-Helsinki/berth-reservations-ui/pull/261) to avoid breaking everything.
> Rename objects and fields reservation -> application

- applications/new_schema.py
- applications/tests/test_applications_new_schema_queries.py
* Add a filter to pass a list of desired statuses and tests
Closes [VEN-455](https://helsinkisolutionoffice.atlassian.net/browse/VEN-455)
```shell
$ pytest applications/tests/test_applications_new_schema_queries.py
```
**Manual testing 👷** 
```graphql
query Applications {
berthApplications(statuses:["PENDING"]) {
edges {
node {
id
status
customer {
id
}
}
}
}
}
```
> VEN-455 | Application status filter

- customers/schema.py
- customers/tests/test_customers_schema.py
- leases/schema.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_queries.py
1. Since ProfileNode is extended, none of its fields could be
non-nullable (i.e. required=True), because then the entire
ProfileNode will be null at the federation level, if the
profile object has no object in our database.
2. Make `BoatNode` actually implement `relay.Node` interface.
> Make all the fields of Profile nodes nullable in our GQL API

- berth_reservations/views.py
- requirements.in
- requirements.txt
- resources/schema.py
- Replace the `image_file` input field for `Harbor` mutations (`create` and `update`) with File `Upload` scalar
**Closes 🙅‍♂** 
**[VEN-405](https://helsinkisolutionoffice.atlassian.net/browse/VEN-405)**
**Related 🤝**
[**[VEN-512](https://helsinkisolutionoffice.atlassian.net/browse/VEN-512)**] Add tests for file upload
N/A (Refer to VEN-512)
**Manual testing 👷**
First, you have to comment/remove the `@login_required` and `@superuser_required` decorators from the [update mutation](https://github.com/City-of-Helsinki/berth-reservations/blob/ven-405/file-upload/resources/schema.py#L510) to avoid having to deal with login with cURL.
To perform an update, execute the following cURL:
```shell
curl localhost:8000/graphql_v2/ \
-H "Content-Type: multipart/form-data" \
-F …
```
> VEN-405 | File Upload for Harbor

- applications/tests/test_applications_new_schema_mutations.py
- applications/tests/test_applications_new_schema_queries.py
- applications/tests/test_reservations_graphql.py
- berth_reservations/tests/conftest.py
- berth_reservations/tests/utils.py
- customers/tests/test_customers_schema.py
- harbors/tests/test_harbors_graphql.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_queries.py
- resources/schema.py
- resources/tests/test_resources_mutations.py
- resources/tests/test_resources_queries.py
1. Switch to using Graphene's test CLient for GQL tests.
2. Initialize clients for anonymous user, regular user, staff user
and superuser as pytest fixtures.
3. Initialize separate clients for old schema and new schema (v2).
Still needs some tests to ensure that `Accept-Language` header works
as expected using the old `GraphQLDjangoTestClient`. Coming in another PR.
```shell
pytest
```
> Refactor GraphQL Client in tests

- applications/models.py
- applications/tests/factories.py
- applications/tests/test_application_models.py
- applications/tests/test_applications_new_schema_queries.py
- leases/schema.py
- leases/tests/test_lease_mutations.py
* Move application `DRAFTED -> OFFER_SENT` when a lease is created
* Move application `DRAFTED -> PENDING` when a drafted lease is deleted
Close [VEN-504](https://helsinkisolutionoffice.atlassian.net/browse/VEN-504)
```shell
pytest leases/tests/test_lease_mutations.py
```
> VEN-504 | Update BerthApplication status on lease changes

- .github/pull_request_template.md
- leases/schema.py
- resources/schema.py
- resources/tests/conftest.py
- resources/tests/test_resources_queries.py
* Expose `berth_leases` on `BerthNode`
* Only allowed for authorised users
If the query is performed without the `leases` field, it will pass for any user. If the `leases` field is added to the query and the user doesn't have `superuser` permissions, it will return an error.
**Closes 🙅**
[VEN-505](https://helsinkisolutionoffice.atlassian.net/browse/VEN-505)
```shell
$ pytest resources/tests/test_resources_queries.py::test_get_berth_with_leases
$ pytest resources/tests/test_resources_queries.py::test_get_berth_with_leases_not_enough_permissions
```
**Manual testing 👷** 
Try the following query in a browser with an existing session and in incognito mode:
```graphql
query BERTH_LEASES {
berth(id: "QmVydGhOb2RlOjMwNWViMDJhLTk2MGUtNDZhNy05YWE5LWVmNWJhNTRmZGRiNA==") { …
```
> VNE-505 | Expose berth leases

- customers/tests/test_customers_schema.py
1. Use GQL classes to generate global IDs
Use GQL classes' properties to generate global IDs instead of
just strings of their names. This way potential change of the
class name will be easier to refactor in places like these.
2. Test extended ProfileNodes can be fetched by federation gateway
**Automated tests :gear:️**
```bash
pytest customers/
```
> Test federated profile

- applications/admin.py
Since we started using django-ilmoitin, we need to pass the enums'
value, when we fire send_notification helper function.
> Fix resend notifications for applications in Django admin

- resources/schema.py
- resources/tests/test_resources_mutations.py
* Update the `create/update_harbor` tests to support `ImageFile` uploads
* Update the `create/update_harbor` tests to support `addHarborMaps` uploads
* Add another `update_harbor` tests for `removeHarborMaps` uploads
* Fix an issue 🐛 that was not saving map instances properly
- **[VEN-512](https://helsinkisolutionoffice.atlassian.net/browse/VEN-512):** Add tests for file upload
- **[VEN-405](https://helsinkisolutionoffice.atlassian.net/browse/VEN-405):** Support file upload for Resources (#160)
- **[VEN-479](https://helsinkisolutionoffice.atlassian.net/browse/VEN-479):** Backend: add maps to harbors / winter storage areas (#161)
```shell
$  pytest resources/tests/test_resources_mutations.py
$ pytest resources/tests/test_resources_mutations.py::test_create_harbor
$ pytest …
```
> VEN-512 | File upload tests

- leases/schema.py
- leases/tests/test_lease_mutations.py
*  Catch the `ValidationError` raised when the `application` passed to a `lease` already has another `lease` assigned.
* Add a test
**[VEN-511](https://helsinkisolutionoffice.atlassian.net/browse/VEN-511):** CreateBerthLease mutation does not check if application has lease already
Sentry [error trace](https://sentry.hel.ninja/aok/berth-api/issues/10542/)
```shell
$ pytest leases/tests/test_lease_mutations.py::test_create_berth_lease_application_already_has_lease
```
> VEN-511 | Check if application already has a lease

- applications/models.py
Temporary measure to avoid validation errors untill the GQL API
is changed accordingly. API uses floats for those which does not
work well with Django's validation for DecimalField.
> Exclude decimal fields from validation in Berth Application

- applications/new_schema.py
- applications/tests/test_applications_new_schema_queries.py
- leases/schema.py
- leases/tests/test_lease_queries.py
* Add a `orderBy` argument to `berthApplications` and `berthLeases` queries
* The `orderBy` parameter takes either `createdAt` (ascending) or `-createdAt` (descending)
* Set `created_at | ASC` as default ordering
* Add tests for custom ordering and deafult ordering
**[VEN-514](https://helsinkisolutionoffice.atlassian.net/browse/VEN-514):** sort berth applications and leases query by the created_at field
```shell
$ pytest applications/tests/test_applications_new_schema_queries.py
$ pytest leases/tests/test_lease_queries.py
```
```graphql
query APPLICATIONS {
berthApplications(orderBy:"-createdAt") {
edges {
node {
createdAt
}
}
}
}
query LEASES {
berthLeases(orderBy:"createdAt") {
edges {
node {
id
createdAt
}
}
}
}
```
**BerthApplications query**
**BerthLeases query**
> VEN-514 | Sort applications and leases by created_at

- applications/new_schema.py
- applications/tests/test_applications_new_schema_mutations.py
- applications/tests/test_applications_new_schema_queries.py
- berth_reservations/tests/conftest.py
- customers/schema.py
- customers/tests/test_customers_schema.py
- leases/schema.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_queries.py
- resources/schema.py
- resources/tests/test_resources_mutations.py
- resources/tests/test_resources_queries.py
- users/decorators.py
- users/fixtures/groups.json
- users/management/commands/set_group_model_permissions.py
- users/tests/test_permission_utils.py
- users/utils.py
- Add Group permission fixtures
- Add a management command to set model permissions
- Add decorators (and util functions) to check for permissions
- Add the required pytest fixtures to test for the new permissions/groups
- Update all the tests checking for permissions to fit the new schema
[VEN-453](https://helsinkisolutionoffice.atlassian.net/browse/VEN-523)
[VEN-363](https://helsinkisolutionoffice.atlassian.net/browse/VEN-363)
```shell
$ pytest
```
1. Load the data from the `perms.json` fixture
```shell
$ python manage.py loaddata groups.json
```
2. Run the script to set the model permissions
```shell
$ python manage.py set_group_model_permissions
```
3. Add your user to the one of the groups via [django admin](http://localhost:8000/admin)
4. Try to access the protected resources
The …
> VEN-453 | User permissions

- applications/tests/test_applications_new_schema_mutations.py
- applications/tests/test_applications_new_schema_queries.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_queries.py
- resources/tests/test_resources_mutations.py
- resources/tests/test_resources_queries.py
Replace hard-coded GQL class names with the real class name taken from `Model._meta`
**[VEN-523](https://helsinkisolutionoffice.atlassian.net/browse/VEN-523)**: Use GQL classes to generate global IDs
**[VEN-509](https://helsinkisolutionoffice.atlassian.net/browse/VEN-509)**: Decoding global IDs has potential problems
```shell
$ pytest
```
> VEN-523 | Replace hard-coded GQL class names with meta names

- berth_reservations/settings.py
- berth_reservations/views.py
- Add more ignores that should be ignored
**[VEN-510](https://helsinkisolutionoffice.atlassian.net/browse/VEN-510)**: PermissionDenied error is sent to sentry
1. Add a print statement to [berth_reservations/views.py#L42](https://github.com/City-of-Helsinki/berth-reservations/blob/9ade74aade04c8c8db232214bc3c991536afad75/berth_reservations/views.py#L42)
2. Execute a restricted query (i.e. `BerthApplications`) from Incognito Mode
3. The print shouldn't be printed
4. Success 👍 
Follows the [OpenCityProfile!130](https://github.com/City-of-Helsinki/open-city-profile/pull/130)
> VEN-510 | Specify errors to be ignored by Sentry

- berth_reservations/settings.py
This will allow us using JWT's `exp` value for up to 60 mins 
in the future. Default `OIDC_LEEWAY` considers them invalid
after 15 mins.
> Allow JWT tokens to be valid for 1 hour

- applications/new_schema.py
- applications/schema.py
- customers/schema.py
- leases/schema.py
- resources/schema.py
- resources/tests/test_resources_mutations.py
- utils/relay.py
- Add a util function to safely decode global GQL ids
- Update mutations to use safe decode of global ids
**[VEN-509](https://helsinkisolutionoffice.atlassian.net/browse/VEN-509):** Decoding global IDs has potential problems.
```shell
$ pytest
```
Execute a mutation that requires decoding an ID.
```graphql
mutation HARBOR {
updateHarbor(input: { id: "clearly_an_invalid_id" }) {
harbor {
id
}
}
}
```
It should return an error: `"Harbor matching query does not exist."`.
> VEN-509 | Safely decode GQL global ids

- resources/models.py
Add the `distinct=True` flag to the number of places `Count` to get the actual number of places.
Run the Harbors query:
```graphql
query HARBORS {
harbors {
edges {
node {
properties {
name
maxWidth
maxDepth
maxLength
numberOfPlaces
}
}
}
}
}
```
the `numberOfPlaces` should seem like reasonable numbers (between 0-250)
**Before**
**After**
> Hotfix: add distinct to places count

- applications/new_schema.py
- applications/tests/test_applications_new_schema_mutations.py
- customers/schema.py
- leases/schema.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_queries.py
- Replace `BerthProfileNode` for `ProfileNode`
- Update corresponding tests
**[VEN-490](https://helsinkisolutionoffice.atlassian.net/browse/VEN-490):** Graph branches point to BerthProfileNode instead of ProfileNode
**[VEN-559](https://helsinkisolutionoffice.atlassian.net/browse/VEN-559):** Decode correct CustomerProfile ID
```shell
$ pytest
```
On `Voyager` check that the only branches pointing at `BerthProfileNode` are the explicit queries, otherwise, you should see:
```
BerthLease.customer: ProfileNode!
BerthApplication.customer: ProfileNode
BoatNode.owner: ProfileNode!
ProfileNode.company: CompanyType
```
> VEN-490 | VEN-559 | Replace BerthProfileNode for ProfileNode

- leases/schema.py
- resources/schema.py
- utils/relay.py
* Add a `nullable` option to the `get_node_from_global_id` util. This allows to have better control on when to raise an error that might return sensitive information to the client
* Update the schemas to pass the tests
**[VEN-562](https://helsinkisolutionoffice.atlassian.net/browse/VEN-562):** Node resolver util should sometimes just return null
```shell
$ pytest
```
> Add nullable option to get node util

- leases/models.py
- leases/schema.py
- leases/tests/test_lease_models.py
- Add a validation for `BerthLease` years
**[VEN-558](https://helsinkisolutionoffice.atlassian.net/browse/VEN-558):** Validate that BerthLease season occurs during the same year
#188 
```shell
$  pytest leases/tests/test_lease_models.py::test_lease_should_be_the_same_year
```
**Error returned on GraphQL**
> VEN-558 | Validate that BerthLease season occurs during the same year

- leases/models.py
- leases/tests/test_lease_models.py
- Raise an error when the `berth/place` is being changed on a lease
**[VEN-569](https://helsinkisolutionoffice.atlassian.net/browse/VEN-569):** Lease shouldn't allow switching to a new place
```shell
$ pytest  leases/tests/test_lease_models.py::test_berth_lease_cannot_update_berth
$ pytest  leases/tests/test_lease_models.py::test_winter_storage_lease_cannot_update_place
```
1. Go to the Lease page on the admin
2. Try to change the `berth/place` assigned to the lease
3. An error should be raised
**Error raised on admin**
> VEN-569 | Avoid leases changing places

- users/management/commands/set_ad_group_mappings.py
- Add a management command (`set_ad_group_mappings`) to create the corresponding `ADGroup`s and `ADGroupMapping`s
**[VEN-363](https://helsinkisolutionoffice.atlassian.net/browse/VEN-363):** Map AD groups from hel.fi accounts to Django permission groups
1. Run the command
```shell
$ python manage.py set_ad_group_mappings
```
2. On the admin, go to [/admin/helusers/adgroupmapping/](http://localhost:8000/admin/helusers/adgroupmapping/)
3. You will see the AD groups mapped to the Venepaikka groups
The command has to be run _after_ group fixtures have been loaded
```shell
$ python manage.py loaddata groups.json
```
> VEN-363 | Map AD groups to Vene groups

- applications/new_schema.py
- applications/tests/test_applications_new_schema_mutations.py
- Add a mutation to delete `BerthApplications`
**[VEN-477](https://helsinkisolutionoffice.atlassian.net/browse/VEN-477):** Mutation to delete an application
```shell
$ pytest applications/tests/test_applications_new_schema_mutations.py
```
```graphql
mutation DeleteBerthApplication($input: DeleteBerthApplicationMutationInput!) {
deleteBerthApplication(input: $input) {
__typename
}
}
```
> VEN-477 | Delete applications

- leases/models.py
- leases/schema.py
- leases/tests/test_lease_models.py
- leases/tests/test_lease_mutations.py
- Add extra validation for leases changing application
- Check that they belong to the same owner
- WSApplication doesn't have a `customer` field, so it can't be checked atm
- Add the `UpdateBerthLeaseMutation`
- Create a separate `BerthLeaseInput` class to share the common input fields between mutations
- Minor changes to `CreateBerthLeaseMutation` to fail faster when the application has no customer
**[VEN-548](https://helsinkisolutionoffice.atlassian.net/browse/VEN-548):** 
```shell
$ pytest leases/tests/test_lease_mutations.py
```
```graphql
mutation UpdateBerthLease($input: UpdateBerthLeaseMutationInput!) {
updateBerthLease(input:$input){
berthLease {
id
startDate
endDate
comment
boat {
id
}
application {
id
customer {
id
}
}
}
}
}
```
```json
{
"id": "<BerthLeaseID>",
"startDate": …
```
> VEN-548 | Update Lease mutation

- resources/schema.py
- resources/tests/test_resources_mutations.py
- Add `depth` to `BerthInput` for `create/udpate` mutations
- Update the test
**[VEN-589](https://helsinkisolutionoffice.atlassian.net/browse/VEN-589):** Add depth to berth mutations
```shell
$ pytest resources/tests/test_resources_mutations.py
```
```graphql
mutation UPDATE_BERTH($input: UpdateBerthMutationInput!) {
updateBerth(input: $input) {
berth {
id
berthType {
id
width
length
depth
mooringType
}
}
}
}
```
```json
{
"input": {
"id":"QmVydGhOb2RlOjMzNDU5NTJhLTNiYzItNDE1NC1hOGJiLWQ5Yjg0NDlmMGI3Mg==",
"mooringType": "STERN_BUOY_PLACE",
"width": 6.66,
"length": 3.33,
"depth": 9.99,
}
}
```
**UpdateBerthMutationInput:**
**CreateBerthMutationInput:**
> VEN-589 | Add depth to berth input

- resources/schema.py
- Change the input type of Berth `number` from `String` to `Int`
**[VEN-590](https://helsinkisolutionoffice.atlassian.net/browse/VEN-590):** AbstractBoatPlaceInput number type is string
```shell
$ pytest
```
**Create berth mutation**
**Update berth mutation**
> VEN-590 | Change berth number from string

- applications/new_schema.py
- applications/tests/test_applications_new_schema_queries.py
- customers/schema.py
- customers/tests/test_customers_queries.py
- leases/schema.py
- leases/tests/test_lease_queries.py
- resources/schema.py
- resources/tests/test_resources_queries.py
- utils/schema.py
* Add `CountConnection` to expose the entity count on GQL connection fields
* Add tests for the connections using it
**[VEN-585](https://helsinkisolutionoffice.atlassian.net/browse/VEN-585):** Add custom connection with count attribute
```shell
$ pytest
```
All the objects exposed as connections extend this class, so you can test with any resource
```graphql
query CONNECTION_TEST {
allHarbors:harbors {
count
totalCount
}
harborsElectricity:harbors(piers_Electricity: true) {
count
totalCount
}
harborsNoElectricity:harbors(piers_Electricity: false) {
count
totalCount
}
}
```
**Result:**
```json
{
"data": {
"allHarbors": {
"count": 42,
"totalCount": 42
},
"harborsElectricity": {
"count": 28,
"totalCount": 42
},
"harborsNoElectricity": {
"count": 16,
"totalCount": 42
}
}
}
```
Some of the …
> VEN-585 | CountConnection

- leases/tests/test_lease_queries.py
- resources/schema.py
- resources/tests/test_resources_mutations.py
- resources/tests/test_resources_queries.py
Hide the `BerthType` logic from the client by exposing the dimensions + mooring type directly on the `BerthNode` rather than having a nested field. When creating or updating a `berth`, only the dimensions and mooring type are expected, not the `berth_type_id` anymore.
When a berth is being created, a `BerthType` with the passed properties will try to be fetched from the DB, if it doesn't exist, a new one will be created and immediately associated with the new `berth`.
When a berth is being updated, a `BerthType` will try to be fetched _with the new properties_ combined with the old ones for the props not provided, if there's no matching `type`, a new one will be created and associated.
**[VEN-591](https://helsinkisolutionoffice.atlassian.net/browse/VEN-591):** Hide BerthType from client …
> VEN-591 | Hide BerthType from client

- leases/models.py
- leases/schema.py
- leases/tests/test_lease_models.py
* Annotate leases that are active
* _Only_ `PAID` leases are active
* Starting at the beginning of the season (if today is before the season starts)
* Start date < today < end date (if today is during the season)
**[VEN-581](https://helsinkisolutionoffice.atlassian.net/browse/VEN-581):** Annotate active leases at the GQL API
```shell
$ pytest leases/tests/test_lease_models.py
```
```graphql
query LEASE {
berthLeases {
edges {
node {
id
isActive
startDate
endDate
status
}
}
}
}
```
**Berth lease node:**
> VEN-581 | Annotate active leases

- payments/enums.py
- payments/migrations/0001_initial.py
- payments/models.py
- payments/schema/__init__.py
- payments/schema/mutations.py
- payments/schema/queries.py
- payments/schema/types.py
- payments/tests/factories.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations.py
- payments/tests/test_payments_queries.py
Rename `ServiceType` to `ProductServiceType` to avoid naming conflicts with the Federated service (Helsinki Profile also has a `ServiceType` enum)
> Hotfix: rename Service enum to avoid naming conflicts

- customers/schema.py
- customers/tests/test_customers_queries.py
- Sort profiles berthApplications by created_at ASC as default
- Add `orderBy` param to profiles berthApplications
https://helsinkisolutionoffice.atlassian.net/browse/VEN-662
`test_customers_queries.py::test_query_extended_profile_applications_order_by_created`
Fire a query against `graphql_v2`
```
query { 
berthProfiles { 
edges { 
node { 
id
comment
berthApplications {
edges {
node {
id
createdAt
}
}
}
}
}
}
}
```
You should see that berthApplications are sorted by createdAt ascending.
Modify query, add param `berthApplications(orderBy: "-createdAt")`, you should see the applications in createdAt descending order.
> VEN-662 | Sort profiles berthApplications by created_at

- resources/schema.py
- Define number_of_marked_places as optional
[VEN-703](https://helsinkisolutionoffice.atlassian.net/browse/VEN-703)
None
Execute following query, it should not return error anymore:
```
query {
winterStorageAreas {
edges {
node {
id
properties {
numberOfMarkedPlaces
sections {
edges {
node {
id
properties {
electricity
gate
summerStorageForDockingEquipment
summerStorageForTrailers
water
__typename
}
__typename
}
__typename
}
__typename
}
__typename
}
__typename
}
__typename
}
__typename
}
}
```
> VEN-703 | numberOfMarkedPlaces crashes WS areas' queries

- applications/admin.py
- Add customer to WinterStorageApplicationAdmin
[VEN-573](https://helsinkisolutionoffice.atlassian.net/browse/VEN-573)
Land to `http://localhost:8000/admin/applications/winterstorageapplication/add/`
Customer should be selectable there.
> VEN-573 | Fix: add customer to WinterStorageApplicationAdmin

- leases/utils.py
- payments/models.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations.py
- payments/utils.py
The function that was being used to calculate the beginning of the season was used both for determine the lease start date but also to just calculate the season start. However, the default start date for a lease should be `today` if `season start < today < season end`, so there were some miscalculations by using the same function.
By adding a `use_default_date` param to the function, we can decide whether to use `today` (given the conditions) or the computed `default` start date.
```shell
$ pytest
```
> [Hotfix] Season date calculation

- applications/new_schema/mutations.py
- applications/tests/test_applications_new_schema_mutations.py
- Add `updateWinterStorageApplication` and `deleteWinterStorageApplication` mutations and tests
- Replace the `to_global_id` being used in the test file to the simplified util function
- Minor function renamings
**[VEN-726](https://helsinkisolutionoffice.atlassian.net/browse/VEN-726):** Schema for winter storage applications
**[VEN-735](https://helsinkisolutionoffice.atlassian.net/browse/VEN-735):** Update WS application
**[VEN-736](https://helsinkisolutionoffice.atlassian.net/browse/VEN-736):** Delete WS application
```shell
$ pytest applications/tests/test_applications_new_schema_mutations.py
```
> VEN-726 | Update/Delete mutations for WSApplications

- customers/schema/mutations.py
* Fix the `updateBoat` mutation: The received `boat_type_id` was tried to be parsed as a `BoatNode.ID` which was causing the API to fail
**[VEN-757](https://helsinkisolutionoffice.atlassian.net/browse/VEN-757):** Updating boat type fails
Test the mutation with the following input:
```json
{
"id": "Qm9hdE5vZGU6NDMzMjQ2YTQtOGU2NS00YjZlLWIxYTQtMDhiMmM1OWU5MTcx",
"boatTypeId": "6",
"registrationNumber": "VEN-101",
"width": 2.5,
"length": 7,
"draught": null,
"weight": null,
"name": "Boaty McBerth",
"model": ""
}
```
> VEN-757 | Update boat type

- berth_reservations/new_schema.py
- requirements.txt
- users/management/commands/set_group_model_permissions.py
* Update the `django-ilmoitin` version to the latest
* Add the `notificationTemplates` query to the API
**[VEN-674](https://helsinkisolutionoffice.atlassian.net/browse/VEN-XXX):** Existing notification templates could be queried via GQL API
```graphql
query Notifications {
notificationTemplates {
edges {
node {
id
preview
translations {
subject
languageCode
preview
bodyText
}
}
}
}
}
```
> VEN-674 | Add django-ilmoitin queries to API

- payments/models.py
- payments/tests/test_payments_models.py
- resources/tests/factories.py
* Multiply the WSProduct price for the dimensions of the WSPlace _if_ the Order has an associated lease
**[VEN-732](https://helsinkisolutionoffice.atlassian.net/browse/VEN-732):** WS orders do not get proper price calculated
WS products have price per square meter. When generating an Order based on WS product AND WS lease, we should take the dimensions (square meters) of the WS place related to the lease and multiply it by the price.
```shell
$ pytest payments/tests/test_payments_models.py::test_order_retrieves_winter_storage_lease
```
> VEN-732 | Calculate correct price for WS orders

- customers/models.py
- customers/schema/__init__.py
- customers/schema/queries.py
- customers/schema/types.py
- customers/tests/test_customers_queries.py
- requirements.txt
- utils/relay.py
1. Upgrade graphene-federation dependency
Newest version of graphene-federation has some bugs fixed,
including the one that caused duplicate "@key" directive
injections into the generated schema.
2. Return federated ProfileNode in our profiles' queries
BerthProfileNode had no connection to the federated ProfileNode
and contained only those CustomerProfile's fields that are stored
in our backend. If we return ProfileNode instead, clients will be
able to get the entire profile object federated across the two
backends. This will also allow the client to use our backend's
profile fields as filters / search fields, when executing the
`berthProfiles` query.
3. Modify filters for berthProfiles query
1. Loosen up the "comment" field filter to check if comment field
contains the passed value (now …
> VEN-381 | Refactor profiles' queries

- applications/new_schema/__init__.py
- applications/schema.py
- leases/schema/__init__.py
- leases/schema/mutations.py
- leases/schema/queries.py
- leases/schema/types.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_queries.py
* Add types, queries and mutations for `WinterStorageLeases`
**[VEN-671](https://helsinkisolutionoffice.atlassian.net/browse/VEN-671):** schema for Winter Storage Leases
```shell
pytest leases/tests/test_lease_queries.py
pytest leases/tests/test_lease_mutations.py
```
For example queries, check the [mutation](https://github.com/City-of-Helsinki/berth-reservations/compare/ven-671/winter-storage-schema?expand=1#diff-3561392d1f187917a71213352b64416e) and [query](https://github.com/City-of-Helsinki/berth-reservations/compare/ven-671/winter-storage-schema?expand=1#diff-1dfc36a6c0e4105ce106c7c5008acfb4) tests
There are some commits/changes from #234 which will be rebased once that PR is merged
> VEN-671 | Winter Storage Leases schema

- requirements.txt
The new version includes a hotfix, that changes the name of the
language enum to a prefixed one - `NotificationTemplateLanguage`.
With this hotfix, our schema will not clash anymore with the
profile's schema and federation gateway will generate the combined
schema successfully.
> Upgrade django-ilmoitin's version to 0.5.3

- resources/admin.py
- resources/models.py
1. Refactor __str__ logic for WS sections and piers 
Since identifier is blankable, if no identifier is passed str
function will fail, as it would return the WS area or harbor
object. With this change we ensure that the return value is
always a string.
2. Use explicit querysets for harbor / ws area in django admin
Django's own querysets result in duplicated results, as each of
the translated object becomes its own choice. Using these basic
querysets gets rid of the duplicated choices.
Go to http://localhost:8040/admin/resources/pier/add/ and check `Harbor` field, it should not have any duplicates.
> Fix piers and ws sections in django admin

- resources/models.py
- resources/schema.py
- resources/tests/test_resources_models.py
- resources/tests/test_resources_queries.py
* Annotate number of unavailable places on piers
**[VEN-762](https://helsinkisolutionoffice.atlassian.net/browse/VEN-762)** 
**[VEN-729](https://helsinkisolutionoffice.atlassian.net/browse/VEN-729)** 
The number of unavailable `winter storage places` will be added on 729 altogether with number of free and total places
```shell
$ pytest resources/tests/test_resources_queries.py::test_get_harbors
$ pytest resources/tests/test_resources_models.py::test_pier_number_of_places
```
```graphql
query Pier {
piers {
edges {
node {
id
properties {
numberOfPlaces
numberOfFreePlaces
numberOfUnavailablePlaces
}
}
}
}
}
```
The number of unavailable `winter storage places` will be added on [VEN-729](https://helsinkisolutionoffice.atlassian.net/browse/VEN-729) altogether with number of free and total …
> VEN-762 | Add number of unavailable places to piers

- payments/schema/mutations.py
- payments/schema/types.py
- payments/tests/test_payments_mutations.py
- payments/tests/test_payments_queries.py
Enable `WinterStorageLease`s for `Order`s
* Add `WinterStorageLeaseNode` to `LeaseUnion`
* Add check for `WSLN` on `create/updateOrder` mutations
* Update tests
**[VEN-765](https://helsinkisolutionoffice.atlassian.net/browse/VEN-765):** WinterLeases missing from Payments schema
```shell
$ pytest payments/tests/test_payments_queries.py
```
```graphql
query ORDERS {
orders {
edges {
node {
id
lease {
... on BerthLeaseNode {
id
}
... on WinterStorageLeaseNode {
id
}
}
}
}
}
}
```
Some of the commits are pending to be merged on #239, they will be gone once the PR is merged and this branch rebased.
> VEN-765 | Winter leases missing from orders

- payments/models.py
- payments/tests/factories.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations.py
- payments/utils.py
- utils/numbers.py
* The tax percentage is now calculated properly and is rounded to the nearest 0.05-decimal
* Add a "round to nearest decimal" option to `utils.numbers.rounded`
* Add a test to explicitly test for order's tax percentage
* Tidy up rounding functions and reuse code
**[VEN-766](https://helsinkisolutionoffice.atlassian.net/browse/VEN-766):** total tax percentage on orders gets wrong value
```shell
$ pytest payments/tests/test_payments_models.py::test_order_tax_percentage
```
> VEN-766 | Fix tax percentage calculation

- resources/schema.py
- resources/tests/test_resources_queries.py
* `WinterStoragePlace`s were missing the newly annotated fields (number of places) that were already available on `WinterStorageArea`
**[VEN-729](https://helsinkisolutionoffice.atlassian.net/browse/VEN-729):** #239 
```shell
$ resources/tests/test_resources_queries.py::test_get_winter_storage_sections
```
```graphql
query WS {
winterStorageSections {
edges {
node {
id
properties {
numberOfPlaces
numberOfFreePlaces
numberOfInactivePlaces
maxWidth
maxLength
}
}
}
}
}
```
> VEN-729 | Add annotated fields to WinterStorageSectionNode

- payments/admin.py
- payments/utils.py
* Check if the value being formatted exists, otherwise return a placeholder value
* Add checks for `total_price` and `total_tax_percentage` on the `payments/admin` to avoid `None` values passed
Go to `admin/payments/order/{order_id}/change/` and `admin/payments/order/add/`, both should work fine
> Hotfix | Pretax price breaking Admin page

- customers/schema/mutations.py
- customers/tests/conftest.py
- customers/tests/test_customers_mutations.py
- users/management/commands/set_group_model_permissions.py
* Add `CUD` mutations for `ProfileNode`
* Minor fixes for some errors left on `BoatNode` mutations
**[VEN-730](https://helsinkisolutionoffice.atlassian.net/browse/VEN-730):** add CRUD mutations for CustomerProfile
```shell
$ pytest customers/tests/test_customers_mutations.py
```
You can find examples on `customers/tests/test_customers_mutations.py`
**createBerthServicesProfile**
**updateBerthServicesProfile**
**deleteBerthServicesProfile**
The `deleteBerthServicesProfile` mutation takes a `deleteOrganization: boolean` input. The mutation will raise an error if it's passed as `true` and the `profile` does not have an organization or if both `deleteOrganization: true` and `organization: {}` inputs are passed.
> VEN-730 | Profile mutations

- leases/utils.py
- payments/models.py
- payments/tests/factories.py
- payments/tests/test_payments_models.py
- payments/utils.py
There was a miscalculation of the winter season by 1 day. With this new calculation, it's also not necessary to check if the order lasts for the full season (`order.is_full_season()`), since it will always yield the correct result, even when "partially" calculating
**[VEN-759](https://helsinkisolutionoffice.atlassian.net/browse/VEN-759):** add season logic to winter storage leases
```shell
$ pytest payments/tests/test_payments_models.py::test_order_winter_storage_lease_right_price_for_full_season
```
> Hotfix | Fix winter storage product season and price calculation

- customers/schema/types.py
- customers/tests/test_customers_queries.py
Make winter storage leases and applications connected to customer
profile available through the GraphQL API.
```bash
pytest customers/tests/test_customers_queries.py
```
> Expose WS leases and applications on ProfileNode

- leases/schema/mutations.py
- leases/tests/test_lease_mutations.py
- payments/management/commands/assign_berth_price_groups.py
- payments/models.py
- resources/models.py
- resources/tests/test_resources_models.py
Generate an `Order` whenever a `winter storage/berth lease` is generated _only_ through the `createXXXLease` mutations.
It will automatically look for a `Berth/WinterStorageProduct` that can be associated to the lease based on the `Harbor/Area` to which the lease place belongs, and a `BerthPriceGroup` for `BerthLease`s.
For `BerthLease`s, it will `get_or_create` the `BerthPriceGroup` every time. In case the price group wouldn't exist, it will be generated, but the `order/lease` creation will fail because of the lack of `BerthProduct`, since there will be no products related to the new price group.
**[VEN-695](https://helsinkisolutionoffice.atlassian.net/browse/VEN-695):** generate an order (a.k.a "invoice") when generating Lease
```shell
pytest -k "test_create_berth_lease_with_order or …
```
> VEN-695 | Generate order with lease

- berth_reservations/tests/factories.py
* Ensure that the `UserFactory.username` and `MunicipalityFactory.id` are unique by using `faker.Sequence`
**[VEN-634](https://helsinkisolutionoffice.atlassian.net/browse/VEN-634):** duplicated municipality key in tests
```shell
pytest
```
From a python shell, execute
```python
from berth_reservations.tests.factories import UserFactory, MunicipalityFactory
UserFactory().username
UserFactory().username
UserFactory().username
MunicipalityFactory().id
MunicipalityFactory().id
MunicipalityFactory().id
```
> Add Sequence to factories giving duplicated results

- leases/schema/mutations.py
- leases/tests/test_lease_mutations.py
* If the product for `harbor, price_group` fails, it tries to use the default product for the `price_gropu`. _ONLY_ works for `BerthProducts` since only those have "default" products.
**[VEN-695](https://helsinkisolutionoffice.atlassian.net/browse/VEN-695):** #248 
```shell
pytest leases/tests/test_lease_mutations.py::test_create_berth_lease_with_order_default_product
```
> VEN-695 | Hotfix | Add fallback for the default product

- resources/schema.py
- resources/tests/test_resources_queries.py
Expose isActive field on WS place node in GQL API
```bash
pytest resources/tests/test_resources_queries.py::test_get_winter_storage_places
```
> Expose isActive field on WS place node in GQL API

- leases/models.py
- leases/schema/types.py
- leases/tests/test_lease_models.py
* Add a `is_active` field to WSLeases
**[VEN-771](https://helsinkisolutionoffice.atlassian.net/browse/VEN-771):**  add "isActive" field to WinterStorageLeaseNode
```shell
$ pytest leases/tests/test_lease_models.py
```
> [VEN-771] | Add is_active field to Winter Storage leases

- payments/models.py
- payments/tests/test_payments_models.py
* Use application boat dimensions as fallback for price: when calculating the price for winter storage orders, if there's no `boat` associated to the `order.lease`, use the `application.boat_width/lenght` since those are required fields
**[VEN-739](https://helsinkisolutionoffice.atlassian.net/browse/VEN-739):** link WS leases simply to WS area if it has no marked places
#254 
#257 
```shell
$ pytest payments/tests/test_payments_models.py::test_order_winter_storage_lease_without_boat_right_price
```
> VEN-739 | Use application boat dimensions as fallback for price

- berth_reservations/schema.py
- payments/schema/__init__.py
- payments/schema/queries.py
- payments/schema/types.py
- payments/tests/conftest.py
- payments/tests/factories.py
- payments/tests/test_payments_queries.py
* Add the `OrderStatus` query, which also allows to check for the order type (`BERTH|WINTER_STORAGE`)
**[VEN-326](https://helsinkisolutionoffice.atlassian.net/browse/VEN-326):** OrderStatus query
#255 
```shell
$ pytest payments/tests/test_payments_queries.py::test_get_order_status
$ pytest payments/tests/test_payments_queries.py::test_get_order_status_order_does_not_exist
```
```graphql
query ORDER_STATUS {
orderStatus(orderNumber: "{order_number}") {
orderType
status
}
}
```
> VEN-326 | Add OrderStatus query

- harbors/schema.py
Prod is broken because WSArea is missing a handful of fields, this PR adds those fields back
```graphql
query WSA {
winterStorageAreas {
edges {
node {
id
properties {
maxWidth
maxLength
availabilityLevel {
title
}
numberOfMarkedPlaces
}
}
}
}
}
```
> Add missing fields to harbors WSArea

- berth_reservations/settings.py
In order to persistent DB connection across requests and make the
application work faster, we need to make CONN_MAX_AGE editable.
Defaults to 1 hour.
> Parametrize DB connection age

- leases/tests/test_lease_mutations.py
`date.replace()` doesn't validate the actual duration of the months/years, so with `relativedelta` we ensure that the dates are added up on a safe way
```shell
$ pytest leases/tests/test_lease_mutations.py::test_update_winter_storage_lease_all_fields
```
> Hotfix | Add months to date on a safe way

- berth_reservations/tests/conftest.py
- payments/apps.py
- payments/notifications.py
- payments/providers/base.py
- payments/schema/mutations.py
- payments/schema/types.py
- payments/tests/conftest.py
- payments/tests/factories.py
- payments/tests/test_bambora_payform.py
- payments/tests/test_payments_mutations.py
- payments/tests/test_payments_mutations_approve_order.py
* Add a mutation to approve orders
The mutation takes a list of order `graphene.ID` and a `dueDate`. If no due date is passed, it takes the one already set on the `order`.
**[VEN-547](https://helsinkisolutionoffice.atlassian.net/browse/VEN-547):**  mutation to finalize lease offer
```shell
$ pytest payments/tests/test_payments_mutations.py
```
Create an order, with a lease, and application. Then execute the following mutation:
```graphql
mutation ApproveOrders($input: ApproveOrderMutationInput!) {
approveOrders(input: $input) {
failedOrders {
id
error
}
}
}
```
```json
{
"input": {
"orders": [
{
"orderId": "",
"email": "foo@bar.com"
}
]
}
}
```
> VEN-547 | Add a mutation to approve orders and send emails

- payments/notifications.py
The config taken from `payments/tests/conftest.py` used on `payments/notifications.py` make the application crash because `conftest` imports `pytest`, which is not present on non-dev environments.
By replacing the imported conf values by hard-coded ones, we avoid problems.
> Remove test reference on payments dummy context

- README.md
- applications/admin.py
- applications/constants.py
- applications/models.py
- applications/notifications.py
- applications/schema.py
- applications/signals.py
- applications/tests/test_application_models.py
- applications/tests/test_applications_notifications.py
- Send different email notification for umarked ws application
- Improve readme, add instructions for test running
[VEN-829](https://helsinkisolutionoffice.atlassian.net/browse/VEN-829)
pytest applications/tests/test_applications_notifications.py::test_unmarked_winter_application_created_notification_is_sent
pytest applications/tests/test_application_models.py::test_winterstorage_application_is_not_unmarked
pytest applications/tests/test_application_models.py::test_unmarked_winterstorage_application_is_unmarked
> VEN-829 | Send different email notification for umarked ws application

- applications/tests/factories.py
- payments/enums.py
- payments/models.py
- payments/notifications/__init__.py
- payments/notifications/dummy_context.py
- payments/notifications/types.py
- payments/schema/mutations.py
- payments/tests/conftest.py
- payments/tests/test_payments_mutations_approve_order.py
- payments/tests/test_payments_order_types.py
- payments/utils.py
* Add an `order_type` prop to the `Order`s to determine which email should be used
The criteria to determine the `order type` is as follows:
* `NEW_BERTH_ORDER` = The order has a `berth lease` and no previous leases for that customer/berth
* `RENEW_BERTH_ORDER` = The order has a `berth lease` and has previous leases for that customer/berth
* `BERTH_SWITCH_ORDER` = The `order.lease.application` has a `berth switch`
* `WINTER_STORAGE_ORDER` = The order has a `winter storage lease`
* `UNMARKED_WINTER_STORAGE_ORDER` = The order has an winter storage application with `area_type == UNMARKED`
* `INVALID` = The order is not associated with any lease
**[VEN-815](https://helsinkisolutionoffice.atlassian.net/browse/VEN-815):** Insert email templates into the database
#280: Mail notification …
> VEN-815 | Order notifications

- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform.py
* Add a fallback language in case an order doesn't have a lease
**[VEN-327](https://helsinkisolutionoffice.atlassian.net/browse/VEN-327):**  send order to Bambora
#255 
```shell
$ pytest payments/tests/test_bambora_payform.py
```
> VEN-327 | Default Order language

- customers/models.py
- customers/tests/test_customer_models.py
- resources/fixtures/helsinki-harbor-resources.json
Last batch of changes critical for the Timmi import
* Remove the logic to identify berths and just try and fetch the specfic berth based on the number and pier identifier
* Handle `ValidationError` when creating leases to dismiss diplicate errors
* Add missing `Merisatama 28 (28) 02` - berth fixture
**[VEN-630](https://helsinkisolutionoffice.atlassian.net/browse/VEN-630)** 
#289 
#291 
```shell
$ pytest customers/tests/test_customer_models.py
```
> Hotfix | VEN-630 | Timmi import

- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform.py
* When a "default" `BerthProduct` (no `harbor` assigned) is being assigned to an order, take the `area` as the harbor associated to the lease
**[VEN-800](https://helsinkisolutionoffice.atlassian.net/browse/VEN-800)** 
#278 
```shell
$ pytest payments/tests/test_bambora_payform.py::test_payload_add_product_default_berth_product
```
> VEN-800 | Use the lease harbor for default berth products

- berth_reservations/tests/conftest.py
- customers/models.py
- leases/schema/mutations.py
- leases/tests/test_lease_mutations.py
- payments/models.py
- payments/tests/conftest.py
- payments/tests/test_payments_models.py
- payments/utils.py
- Company customers pay x2 prices
- Non-billable customers do not pay at all, order should show all prices and taxes as 0 and get marked PAID upon creation
**[VEN-684](https://helsinkisolutionoffice.atlassian.net/browse/VEN-684)** 
Several new tests in:
`leases/tests/test_lease_mutations.py`
`payments/tests/test_payments_models.py`
It's hard to test without the whole payment process in place, should be tested once it's implemented.
> VEN-684 | Add pricing rules for organization customers

- harbors/fixtures/helsinki-winter-areas.json
- resources/fixtures/helsinki-ws-resources.json
* Add Hernesaari and Merisatama `WinterStorageArea`s and unmarked places
```shell
$ python manage.py loaddata helsinki-ws-resources
$ python manage.py loaddata helsinki-winter-areas
```
Check the Django admin on `Harbors -> Winter Storage Areas` and `Resources -> Winter Storage Areas`
As per the admins:
* Hernesaari: no water, no electricity, no gate, no summer storage for anything, number of unmarked places: we don't know, the area is 8000 m2 (I estimated 500 places)
* Merisatama: yes water, no electricity, no gate, no summer storage for anything, number of unmarked places: 27
> Hotfix: Add Hernesaari and Merisatama winter areas

- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform.py
* Remove the state transition (to cancelled) when the payment fails
**[VEN-878](https://helsinkisolutionoffice.atlassian.net/browse/VEN-878):** Remove cancel payment handling
```shell
$ pytest payments/tests/test_bambora_payform.py::test_handle_success_request_payment_failed
```
> VEN-878 | Remove cancel payment handling

- payments/providers/bambora_payform.py
* Replace the date sent as part of the order number with the actual timestamp
**[VEN-812](https://helsinkisolutionoffice.atlassian.net/browse/VEN-812)** 
#305
The order number sent to Bambora used only the date instead of the timestamp
> VEN-812 | Hotfix | Order creation timestamp

- leases/models.py
When a `WSLease` is associated to a `section` instead of a `place`, it was just showing `None`.
Go to the `WinterStorageLease` django section
> Hotfix | Fix WSLease str method

- leases/tests/test_lease_mutations.py
- payments/admin.py
- payments/models.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations.py
* Remove partial price calculation for season products
**[VEN-891](https://helsinkisolutionoffice.atlassian.net/browse/VEN-891):** Full price for season products
```shell
$ pytest
```
1. Create an application and lease for a berth/WS place
2. Create a berth/ws product for the place you selected
3. From the Django admin, go to create an order and assign it to the lease and product you generated
4. Hit `Save and continue editing`
5. The price should be the same as the product if you created a berth order. If you created a ws order, it would be equivalent to `boat lenght * width * product price`
6. Add an `OrderLine` for a `season` product
7. The price should be the same for the order line, the `order` price should've changed and would be `order price + order line price`
Working example:
> VEN-891 | Fixed season prices

- payments/models.py
- payments/providers/bambora_payform.py
We disabled cancelling payments from Bambora `success` request, but forgot about the `notify` request. In some cases where the payment was cancelled, the `Order` (and lease and application) would be marked as `rejected`.
```shell
$ pytest payments/tests/test_bambora_payform.py::test_handle_notify_request_payment_failed
```
> Hotifx | Remove payment cancel from notify

- harbors/fixtures/helsinki-harbors.json
The actual changes were this:
* Add the disabled flag to the fixture (`"model": "harbors.harbor", "pk": 16`)
```json
"disabled": true,
```
* Remove all the available places from Merihaan 13
```json
"availability_level": null,
"number_of_places": null,
"maximum_width": null,
"maximum_length": null,
"maximum_depth": null,
```
**[VEN-888](https://helsinkisolutionoffice.atlassian.net/browse/VEN-888):** Disable Merihaan laituri (Hakaniemenranta 13) from berth applications
1. Run the command to load the fixtures
2. Run the command to load images
3. Check the [Harbor page](http://localhost:8000/admin/harbors/harbor/16/change/)
```shell
$ python manage.py loaddata helsinki-harbors
$ python manage.py harbors_add_helsinki_harbors_images
```
The whole file was changed because it was using a …
> Disable the Merihaan 13 harbor and remove available places

- payments/models.py
- payments/schema/mutations.py
- payments/tests/test_bambora_payform.py
- payments/tests/test_payments_mutations.py
* Add a mutation to cancel an order (intended to be used by the customer UI)
**[VEN-883](https://helsinkisolutionoffice.atlassian.net/browse/VEN-883):** Mutation to cancel orders
```shell
$ pytest payments/tests/test_payments_mutations.py::test_cancel_order
$ pytest payments/tests/test_payments_mutations.py::test_cancel_order_invalid_status
$ pytest payments/tests/test_payments_mutations.py::test_cancel_order_does_not_exist
```
> VEN-883 | Add mutation to cancel an order

- resources/fixtures/helsinki-ws-resources.json
* Add a section for the Merisatama `WSArea`
**[VEN-917](https://helsinkisolutionoffice.atlassian.net/browse/VEN-912)** 
1. Load the fixture `python manage.py loaddata helsinki-ws-resources`
2. Check that the section was added
```graphql
query WSS {
winterStorageArea(id: "V2ludGVyU3RvcmFnZUFyZWFOb2RlOjM4OTU1MzcxLTRkZDItNDMyMS04OTk0LWY0YjUyYzgxYWE0MQ==") {
properties {
sections {
edges {
node {
id
properties {
identifier
}
}
}
}
}
}
}
```
> Hotifx | VEN-917 | Add default section for Merisatama

- CHANGELOG.md
- applications/admin.py
- customers/admin.py
- leases/admin.py
- payments/admin.py
- resources/admin.py
* Add more details to Application list and detail
* Add WinterStorage and Order details to customer view
* Add a default prefetch language for WSAreas (fixes VEN-660)
* Add details to lease admin
* Add a base CHANGELOG 
**[VEN-875](https://helsinkisolutionoffice.atlassian.net/browse/VEN-875)** 
**[VEN-660](https://helsinkisolutionoffice.atlassian.net/browse/VEN-660):** 
* Go through the Application (list and detail), Leases (list and detail), and Customer (detail) pages, you should see more items on the tables
* Go to `resources/winterstoragearea/`, it should show 14 items
Winter storage areas (resources) now shows the full list
Berth applications
Winter Storage applications
Winter Storage leases
> VEN-875 | Django admin improvements

- payments/schema/mutations.py
- payments/tests/conftest.py
- payments/tests/test_payments_mutations.py
* Raise an error when an unmarked ws place order is being cancelled
**[VEN-883](https://helsinkisolutionoffice.atlassian.net/browse/VEN-883)** 
#326 
```shell
$ pytest payments/tests/test_payments_mutations.py::test_cancel_unmarked_order_fails
```
> VEN-883 | Check if the order is for an unmarked place

- Dockerfile
- docker/postgres/Dockerfile
Add postgresql-client to docker image, needed for the staging and prod db migrations. Also upgrade local postgres docker to use the same version as in prod.
> Add postgresql-client to docker image

- applications/constants.py
- applications/models.py
- applications/new_schema/mutations.py
- applications/notifications.py
- applications/signals.py
- applications/tests/test_applications_new_schema_mutations.py
- applications/tests/test_applications_notifications.py
- Add reject berth application mutation
- Send application rejected email on mutation
**[VEN-914](https://helsinkisolutionoffice.atlassian.net/browse/VEN-914)** 
```
mutation {
rejectBerthApplication(input: {id: "QmVydGhBcHBsaWNhdGlvbk5vZGU6Mg=="}) {
__typename
}
}
```
Two new test cases in `applications/tests/test_applications_new_schema_mutations.py`
One new test case in `applications/tests/test_applications_notifications.py`
> VEN-914 | Add reject berth application mutation

- leases/models.py
- leases/tests/test_lease_models.py
- payments/migrations/0012_add_storage_on_ice_product.py
- payments/tests/test_payments_models.py
* Check that leases don't last for over a year
**[VEN-699](https://helsinkisolutionoffice.atlassian.net/browse/VEN-699):** Restrict Leases duration to one year
```shell
$ pytest leases/tests/test_lease_models.py::test_winter_storage_lease_over_a_year_raise_error
$ pytest leases/tests/test_lease_models.py::test_winter_storage_lease_one_year_no_error
```
1. Go to the GraphQL API
2. Try to create a lease
3. The API should return a message error: `Lease cannot last for more than a year`
```graphql
mutation CreateWinterStorageLease($input: CreateWinterStorageLeaseMutationInput!) {
createWinterStorageLease(input: $input) {
winterStorageLease {
id
startDate
endDate
}
}
}
```
```json
{
"input": {
"applicationId": "",
"sectionId": "V2ludGVyU3RvcmFnZVNlY3Rpb25Ob2RlOjQ2NTAxY2Q3LWU3MzAtNGZhZi05YTc5LWF …
```
> VEN-699 | Check that leases don't last for over a year

- .gitlab-ci.yml
- berth_reservations/settings.py
Add csrf header and x-forwarded-for settings and session cookie settings to allow django admin to work under the api.hel.fi reverse proxy.
* Ship to production, and check that django admin ui works.
> add production csrf config

- .gitlab-ci.yml
- .prod/on_deploy.sh
- .prod/on_initialize.sh
- .prod/uwsgi.ini
- Dockerfile
Cleanup leftovers from the migration work:
* Reduce uwsgi log spam by ignoring errors about clients dropping connections
* Remove postgres-cmd-line tools from prod image
* Remove sticker assignment management command
* Disable db initialization fixture as it does not work properly, and staging and prod already have data in the db.
> Cleanup after migration

- .prod/uwsgi.ini
When the container started up, we got SSL errors from db queries, due to the context being forked to multiple uwsgi worker threads. Lazy-load the apps in each worker to avoid this.
* Deploy app to staging with this fix included
* Make multiple api calls to it right after deployment is completed
* Check that no errors like this are on the logs:
`psycopg2.OperationalError: SSL error: decryption failed or bad record mac`
`psycopg2.OperationalError: SSL SYSCALL error: EOF detected `
> Lazy load apps in uwsgi to avoid ssl errors in db connections

- berth_reservations/exceptions.py
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- payments/schema/mutations.py
Adds a `type` field to the extensions that graphql emits in the error response. This way we can differentiate between actually "unexpected" errors and errors that we caught but specifically forward to the frontend.
> Improve vene-specific GraphQL exceptions

- customers/services/profile.py
- customers/tests/test_profile_service.py
- leases/schema/mutations.py
- leases/services/invoice.py
- leases/tests/test_lease_mutations_send_invoices.py
- leases/tests/test_send_berth_invoice_service.py
* Since Federation strips the profile token before it reaches our backend, we need to receive it as an input for the mutations that require it.
* The same way [Youth Membership](https://github.com/City-of-Helsinki/youth-membership/blob/develop/youths/schema/mutations.py#L187-L189) does it
**[VEN-843](https://helsinkisolutionoffice.atlassian.net/browse/VEN-843)**: Send invoice for existing berth leases 
```shell
$ pytest customers/tests/test_profile_service.py
$ pytest leases/tests/test_lease_mutations_send_invoices.py
$ pytest leases/tests/test_send_berth_invoice_service.py
```
> VEN-843 | Profile token

- leases/services/invoice.py
* Handle the case when a lease's customer does not have a profile on the Profile backend
#365 
#382 
#388
> VEN-843 | Fail the lease if it's not connected to a customer

- templates/email/messages/additional_service_invoice_fi.html
- templates/email/messages/berth_none_offered_fi.html
* Adjust colspan in `additional_service_invoice`
* Make `additional_service_invoice` correspond to the design
* Fix `berth_none_offered` address
**[VEN-981](https://helsinkisolutionoffice.atlassian.net/browse/VEN-981):** Create email template for additional service invoice
**[VEN-994](https://helsinkisolutionoffice.atlassian.net/browse/VEN-994):** Email template for "no berth to assign" case
> VEN-981, VEN-994 | Email template tweaks

- leases/models.py
- leases/schema/queries.py
- leases/schema/types.py
- leases/services/invoice.py
- leases/tests/test_lease_queries.py
* Add a preview query for invoicing to show expected leases
**[VEN-843](https://helsinkisolutionoffice.atlassian.net/browse/VEN-843):** Send invoice for existing berth leases
```shell
$ pytest leases/tests/test_lease_queries.py::test_query_send_berth_invoice_preview
```
```graphql
query SendBerthInvoicePreview {
sendBerthInvoicePreview {
expectedLeases
}
}
```
> VEN-843 | Preview invoice query

- locale/fi/LC_MESSAGES/django.po
- payments/notifications/dummy_context.py
- payments/tests/conftest.py
- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/utils.py
- scripts/load_notification_templates.py
- templates/email/messages/additional_service_invoice_fi.html
- Take additional invoice email template into use (only FI)
**[VEN-1016](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1016)** 
- generate and load email templates
- go to http://localhost:8000/admin/django_ilmoitin/notificationtemplate/
- Select "Additional product order approved" and hit "Preview"
- You should see the template in action
> VEN-1016 | Integrate additional invoice email template

- leases/services/invoice.py
When creating the lease, we are just copying the previous one which will
be on paid status. For proper bookkeeping, we should set it as drafted
to follow the correct flow from drafted -> offered/error -> paid/rejected.
The lease would in any case be marked as offered/error by the script,
but better to follow the right steps.
After running the script, check the `Lease changes` on the new lease. You should see the transition from `drafted -> offered`
**For example:**
**From local testing:**
> VEN-843 | Set the correct lease status on creation

- payments/admin.py
- payments/models.py
- payments/tests/test_payments_models.py
When a payment is made for a lease which doesn't have an application associated (as is the case with the Timmi leases), it will raise a 500-Server Error because it fails to set the application to handled status.
**[VEN-1043](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1043):** Updating applications on payment success
```shell
$ pytest payments/tests/test_payments_models.py::test_order_set_status_no_application
```
> VEN-1043 | Update payment application status

- payments/models.py
- payments/providers/bambora_payform.py
* Update the product name that is sent to Bambora to make it clearer for the user
**[VEN-1050](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1050):** Bambora payment details contain prices for all tiers
**Berth product:**
**Winter storage product:**
> VEN-1050 | Add place name as product name

- templates/email/messages/berth_application_confirmation_en.html
- templates/email/messages/berth_application_confirmation_fi.html
- templates/email/messages/berth_application_confirmation_sv.html
* Check if the `berth_switch` has a `reason` to avoid failing calling `.title` if `reason is None`
https://sentry.hel.ninja/aok/berth-api/issues/12382/
> Add check for berth switch emails

- payments/tests/test_payments_models.py
Tests started failing this morning when generated berth lease end occurs in 2021. Fixed by @freeze_time.
> Fix test failure when generated berth lease start and end year are different

- contracts/management/commands/generate_missing_contracts.py
* Add a `status=PAID` filter to the queryset
* Add an optional `year` flag to specify which season should be generated
> HOTFIX | Add extra flags to contract generating script

- leases/notifications/dummy_context.py
- leases/services/invoice.py
- templates/email/messages/automatic_invoicing_email_admins_en.html
- templates/email/messages/automatic_invoicing_email_admins_fi.html
- templates/email/plain_messages/automatic_invoicing_email_admins_en.txt
- templates/email/plain_messages/automatic_invoicing_email_admins_fi.txt
* Increase the error limit to 100
* Ignore counting errors if they're due to a customer is missing email
* Send the email to the admins also when the proccess fails because it hits the error limit
Email notice when the process fails
> HOTFIX | Invoicing fixes

- contracts/admin.py
- leases/admin.py
- payments/providers/bambora_payform.py
* When taking the fields form the order, make sure that they're not empty to avoid failing
> HOTFIX | Check that the fields exist when creating an order

- payments/admin.py
- payments/models.py
- payments/schema/types.py
* Add a `paid_at` prop to the `Order` model
* Add the prop to the `OrderNode` type
* Add details about `OrderLogEntry` to Django Admin
```graphql
query Leases {
orders {
edges {
node {
id
paidAt
}
}
}
}
```
> Order paid_at

- berth_reservations/logging.py
- berth_reservations/settings.py
* Ignore the `healthz` and `readiness` requests
* Try parsing the request body as JSON for nicer readability
> Feature | Improve request logging

- resources/schema/queries.py
- resources/schema/types.py
- resources/tests/test_resources_queries.py
Enables filtering berths by harbor and pier, and piers by harbor. This enables simplifying deeply nested queries on the FE.
> Add filtering options to piers and berths

- payments/admin.py
- payments/models.py
- payments/schema/types.py
- payments/tests/test_payments_models.py
* Add a `cancelledAt` and `rejectedAt` props to the `Order` model and node
* Update the `paidAt` prop to a model annotation for better performance
**[VEN-1069](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1069):** Add cancelled_at to order
```shell
$ pytest payments/tests/test_payments_models.py::test_order_paid_and_created
```
**Fields on django admin**
> VEN-1069 | Cancelled and rejected order dates

- payments/providers/base.py
- payments/utils.py
- templates/email/messages/berth_offer_new_en.html
- templates/email/messages/berth_offer_new_fi.html
- templates/email/messages/berth_offer_new_sv.html
- templates/email/messages/berth_offer_switch_en.html
- templates/email/messages/berth_offer_switch_fi.html
- templates/email/messages/berth_offer_switch_sv.html
Re-enabled `cancel_url` in relevant email templates.
**[VEN-1057](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1057): Enable cancel_url on the emails**
**[VEN-913](https://helsinkisolutionoffice.atlassian.net/browse/VEN-913): Cancel order page**
Should be merged after https://github.com/City-of-Helsinki/berth-reservations-ui/pull/353
> Add cancel_url to invoice emails

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- payments/notifications/dummy_context.py
- payments/notifications/types.py
- scripts/load_notification_templates.py
* Add order cancellation notification type and dummy context
**[VEN-1063](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1063):** Order cancellation confirmation email
#440 
1. Load the email templates
```
python ./scripts/load_notification_templates.py
```
2. From Django admin, go to the `Confirmation` template
> VEN-1063 | Add order cancellation notification type and dummy context

- berth_reservations/tests/conftest.py
- payments/notifications/types.py
- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
- payments/utils.py
* Send an order cancellation email
* Rename the `NotificationType` to make more sense and delegate the email subject to the right function
**[VEN-1062](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1062):** Send cancellation notice to customer
```shell
$ pytest payments/tests/test_payments_mutations.py::test_cancel_order
```
1. Generate an order with a lease, the order should be `WAITING` status and lease on `OFFERED` (add an email to `order.customer_email`)
2. From the customer API (`/graphql`), execute the following mutation:
```graphql
mutation CancelOrder {
cancelOrder(input: {orderNumber: ""}) {
__typename
}
}
```
3. You should see the confirmation email on the console
> VEN-1062 | Send an order cancellation email

- .prod/on_deploy.sh
- payments/notifications/dummy_context.py
- resources/models.py
* Replace the `models.Manager` for parler's `TranslatableManager` since this breaks the Django Admin
> HOTFIX | Harbor manager

- .github/workflows/staging.yml
Starts to use KuVa Tunnistamo in review and staging to allow testing of review envs with authentication.
**[DEVOPS-237](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-237):** 
Check that login works. Probably not testable in the review environment.
> KuVa Tunnistamo to staging

- payments/models.py
- payments/schema/mutations.py
- payments/tests/conftest.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/utils.py
- utils/numbers.py
* When resending the invoice, it checks if it has `error` state and sets it to `waiting/offered` status in case it has been fixed
* Enable order status changes from `error -> waiting`
* Add a check to raise an error if the order doesn't have an email when sending the invoice
**[VEN-1071](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1071):** Admins can't send fixed invoices
```shell
$ python payments/tests/test_payments_mutations_resend_order.py
```
1. Set an order and the lease to `ERROR` states
2. Exectue the the first mutation for that order
```graphql
mutation RESEND_ORDER_MUTATION($input: ResendOrderMutationInput!) {
resendOrder(input: $input) {
failedOrders {
id
error
}
sentOrders
}
}
```
```json
{
"input": {
"orders": ["..."],
"dueDate": "2021-02-15"
}
}
```
3. Check the …
> VEN-1071 | Resend error invoices

- leases/services/invoice.py
- payments/tests/test_payments_utils.py
- payments/utils.py
- utils/email.py
* Raise an error when the `send_payment_notification` receives an `@example.com` email
**[VEN-1071](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1071)** 
#455 
#457 
```shell
$ pytest payments/tests/test_payments_utils.py::test_send_payment_notification_example_email
```
> VEN-1071 | Exclude example.com emails

- payments/models.py
- payments/tests/test_payments_mutations.py
Admins need to be able to move order from error to paid_manually status
**[VEN-1063](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1063):**
> allow order.status transition from error to paid_manually

- leases/notifications/dummy_context.py
- leases/notifications/types.py
- leases/schema/mutations.py
- leases/schema/utils.py
- leases/tests/conftest.py
- leases/tests/test_lease_mutations.py
- scripts/load_notification_templates.py
- templates/email/messages/ws_lease_termination_confirmation_en.html
- templates/email/messages/ws_lease_termination_confirmation_fi.html
- templates/email/messages/ws_lease_termination_confirmation_sv.html
- Add confirmation email for terminating winter storage leases
- Add generic function to terminate leases
- Add mutation to terminate winter leases 
**[VEN-935](https://helsinkisolutionoffice.atlassian.net/browse/VEN-935):** Mutation to terminate a lease
#469 
```shell
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_with_application
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_without_application
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_with_due_date
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_not_enough_permissions
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_doesnt_exist
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_no_email_no_token
``` …
> VEN-935 | Terminate winter lease

- leases/admin.py
- payments/admin.py
For debugging similar cases in the future, it would be useful to be able to filter orders by due_date and leases by start_date in the django admin.
**[VEN-1177](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1177):**
> date_hierarchy in django admin for orders and leases

- applications/new_schema/types.py
- applications/tests/conftest.py
- applications/tests/test_applications_new_schema_berth_queries.py
This filter will return:
- true: all applications with a non-empty `application_code`.
- false: all applications with an empty `applicaiton_code`.
**[VEN-1085](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1085)** 
**[VEN-1093](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1093)** 
```
pytest applications/tests/test_applications_new_schema_berth_queries.py::test_berth_applications_application_code_filter
pytest applications/tests/test_applications_new_schema_berth_queries.py::test_berth_applications_application_code_filter_empty_string
pytest applications/tests/test_applications_new_schema_berth_queries.py::test_berth_applications_application_code_filter_false
```
> VEN-1085 | Add boolean filter for application_code

- leases/schema/mutations.py
- leases/services/invoice.py
- leases/tests/test_lease_mutations.py
- payments/tests/conftest.py
- payments/tests/test_payments_utils.py
- payments/utils.py
Do not send invoices if an order customer is non-billable and set the order status as paid when accepting the order.
**[VEN-1091](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1091):** 
```
pytest payments/tests/test_payments_utils.py::test_approve_order_with_non_billable_customer
```
> VEN-1091 | Don't send invoice to non-billable customers

- leases/consts.py
- resources/models.py
- resources/tests/test_resources_models.py
* Mark refused berths (and ws places) as available
When a berth was marked as refused but still had a paid lease on the
previous season, the checks were taking that as a valid condition and
kept the berth marked as not available.
Now, we discard the leases from the previous season that have already
been renewed so we only consider either:
1) leases on the current (or upcoming) season which have not been
terminated or refused
2) leases on the previous season which have not been renewed and have
been paid
**[VEN-1137](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1137):** Mark refused leases as available berths
```
pytest resources/tests/test_resources_models.py
```
1. Generate a lease
2. Check the berth, it should be `not available`
3. Reject the lease (through the …
> VEN-1137 | Mark refused berths available

- leases/schema/utils.py
- leases/tests/test_lease_mutations.py
When a lease is terminated, if no end date was provided, adjust the default end_date to be `max(today, start_of_the_lease_season)`. This needs to be adjusted for the special case if a lease is terminated before the season starts, so that the condition `start_date>=end_date` is fulfilled.
**[VEN-1179](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1179):** 
```
pytest leases/tests/test_lease_mutations.py::test_terminate_berth_lease_before_season
pytest leases/tests/test_lease_mutations.py::test_terminate_ws_lease_before_season
```
Terminate a:
- Berth lease before the berth season starts.
- Winter storage lease before the winter storage season starts.
and the end date should be set to the start of the season.
> VEN-1179 | Adjust the lease termination end_date

- leases/models.py
- leases/tests/test_lease_models.py
* Consider future leases as available if it's one of the `ACTIVE_LEASE_STATUSES` (drafted, offered, paid, error)
**[VEN-1133](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1133):** Future leases are not active
```
pytest leases/tests/test_lease_models.py::test_berth_lease_is_active_before_season
```
Execute the query, all the leases should be `isActive = true`
```graphql
query Lease {
berthLeases(startYear: 2021, first: 3, statuses: [OFFERED, DRAFTED]) {
count
edges {
node {
status
isActive
}
}
}
}
```
> VEN-1133 | Mark drafted, offered, and error leases as active

- leases/models.py
- leases/tests/test_lease_models.py
Allows overlapping project A end date & project B start date
**[VEN-700](https://helsinkisolutionoffice.atlassian.net/browse/VEN-700):** 
```
pytest leases/tests/test_lease_models.py::test_allow_berth_lease_to_start_on_the_day_another_ends
```
> VEN-700 | Allow leases to start on the day another lease ends

- leases/notifications/dummy_context.py
- templates/email/messages/berth_lease_termination_confirmation_en.html
- templates/email/messages/berth_lease_termination_confirmation_fi.html
- templates/email/messages/berth_lease_termination_confirmation_sv.html
- templates/email/messages/general_cancel_confirmation_en.html
- templates/email/messages/general_cancel_confirmation_fi.html
- templates/email/messages/general_cancel_confirmation_sv.html
- templates/email/messages/ws_lease_termination_confirmation_en.html
- templates/email/messages/ws_lease_termination_confirmation_fi.html
- templates/email/messages/ws_lease_termination_confirmation_sv.html
* Rename `cancellation_date -> cancelled_at` variable on termination template
For consistency with the other timestamp variables, we will rename this to `cancelled_at`
**[VEN-935](https://helsinkisolutionoffice.atlassian.net/browse/VEN-935):** Mutation to terminate a lease
#469 
#470 
1. Go to the template on the admin
[http://localhost:8000/admin/django_ilmoitin/notificationtemplate/12/change/?language=en](http://localhost:8000/admin/django_ilmoitin/notificationtemplate/12/change/?language=en)
2. Hit `Preview`, the template should render correctly
> VEN-935 | Rename cancelled_at variable on termination template

- contracts/services/visma_contract.py
* Make the Visma test SSN config optional
> Hotfix | Make the Visma test SSN config optional

- resources/schema/queries.py
- resources/tests/test_resources_queries.py
Add isInvoiceable query for berths.
**[VEN-1176](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1176)** 
```
pytest resources/tests/test_resources_queries.py::test_berth_is_invoiceable
```
```
query getBerths {
berths(isInvoiceable: false) {
count
totalCount
}
}
```
> VEN-1176 | Add is_invoiceable query for berths

- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform_refund.py
- payments/tests/test_payments_mutations_refunds.py
* Replace the refunded amount for the actual order total, not just the product price
* Add the email to the payload for cases when the refund has to be confirmed by the customer
**[VEN-1159](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1159)**
#485 
```shell
$ pytest payments/tests/test_bambora_payform_refund.py
```
> VEN-1159 | Fix the VismaPay payload fields

- resources/schema/utils.py
- resources/tests/test_resources_queries.py
Admins want to see also berths that are too short. Highlighting will be done in UI.
**[VEN-1251](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1251):**
> VEN-1251: do not filter by berth length when querying berths for an application

- payments/providers/bambora_payform.py
* Fix the amount saved on the Refund model
The correct amount was being sent to VismaPay, but not set on the `OrderRefund` model we save on our db.
**[VEN-1159](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1159)** 
#485 
#499
> VEN-1159 | Fix the amount saved on the Refund model

- payments/schema/mutations.py
- payments/schema/types.py
- payments/tests/test_payments_mutations_accept_berth_switch_offer.py
- payments/tests/test_payments_queries_berth_switch_offers.py
Add a mutation for accepting & rejecting offers. The accepting uses the logic of berth switching from #487.
Rejecting will mark the offer as REJECTED and nothing else is changed.
The mutation will return the offer and the new lease.
**[VEN-1201](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1201)** 
```
pytest test_payments_mutations_accept_berth_switch_offer.py
```
- Restore the permission check for `BerthSwitchOfferNode` when the customer login is sorted out.
>  VEN-1201 | Accept/reject switch offer

- resources/models.py
- resources/tests/test_resources_models.py
This was done as a hotfix release ([release-1.3.5-hotfix](https://github.com/City-of-Helsinki/berth-reservations/releases/tag/release-1.3.5-hotfix)). This is now the proper implementation of the fix.
A few extra considerations had to be taken: for leases which end during
the season, the berth should be available ONLY after the day when the
lease ends (e.g. if the lease ends on 10.7, the berth will not be
available until 10.7, after that, it will be marked as available).
```shell
$ pytest resources/tests/test_resources_models.py::test_berth_is_not_available_ends_during_season_before_lease_ends
$ pytest resources/tests/test_resources_models.py::test_berth_is_available_ends_during_season_after_lease_ends
```
> Tech | Fix algorithm to determine if berth is available

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
Ensure that email subjects have translations. Removed / fixed all fuzzy translations so that at least there are no incorrect translations in the system.
**[VEN-1225](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1225)**
> VEN-1225 | Add translations for Finnish and Swedish

- customers/schema/types.py
- customers/tests/test_customers_queries.py
- payments/schema/types.py
- payments/tests/test_payments_queries.py
- Allow customers to view their own Orders and Offers.
- Add BerthSwitchOffer to be queried through ProfileNode.
**[VEN-1216](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1216): Query for the customer personal information** 
```
pytest customers/tests/test_customers_queries.py::test_query_berth_profile_self_user
```
> VEN-1216 | Update user profile query permissions and add offers to profile query

- payments/admin.py
- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform.py
- payments/tests/test_payments_product_ids.py
- payments/utils.py
Storage on ice products have a different `function area` (Toimintoalue), even when the corresponding area is a harbor (coming from the lease). This fixes the calculation of the Talpa ID for storage on ice additional products.
* Extract `resolve_area` to a separate util
* Refactor the tests for `product_id`
**[VEN-1277](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1277):** Storing on ice needs proper Talpa ID
```shell
$ pytest payments/tests/test_payments_product_ids.py
$ pytest payments/tests/test_bambora_payform.py::test_payload_additional_product_order
```
Check the Talpa product ID on the Django Admin for this order: https://berth-reservations-ven-1277-fix-storage-o-6b.test.kuva.hel.ninja/admin/payments/order/17967a8a-96fe-4e67-81bd-1f97194f96ab/change/
The credentials are: …
> VEN-1277 | Fix Talpa ID for storage on ice

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
- payments/management/commands/expire_too_old_offers.py
- payments/models.py
- payments/tests/test_payments_offer_expiration.py
Also fix cronjob names in kubernetes config
**[VEN-1208](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1208):** 
In Django admin, verify that offer 3a054023-8f6b-4b4b-b701-42576471ad81 status is OFFERED and due_date is 15.3.2021
In pod, run:
python manage.py expire_too_old_offers
Last line of output should be: "expire_too_old_offers done, 1 object(s) were expired."
Verify that the offer status has changed to expired.
> VEN-1208: fix expire old offers cronjob to use proper OfferStatus

- payments/models.py
* Use `set_status` for expiring orders instead of manually setting the status
> VEN-1208 | Proper status transition for expiring offers

- payments/admin.py
* Pass the correct property to the `get_area` so the Talpa ID is shown properly
> VEN-1277 | Get the correct Talpa ID on Order admin

- payments/tests/test_bambora_payform.py
* Some tests which should not have storage on ice were getting the value because of the randomness, this makes sure that we don't get it.
```shell
$ pytest payments/tests/test_bambora_payform.py::test_payload_additional_product_order
```
> VEN-1277 | Fix test for additional product storage on ice payload

- payments/schema/queries.py
- payments/schema/types.py
- payments/tests/test_payments_queries.py
Add berth information to OrderDetailsType. The 3 added fields include:
- harbor name
- pier identifier
- berth number
**[VEN-1268](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1268): Add berth information to order details** 
```
pytest payments/tests/test_payments_queries.py::test_get_order_status
```
> VEN-1268 | Add berth information to order details

- payments/schema/queries.py
- payments/schema/types.py
- payments/tests/test_payments_queries.py
* Add `is_application_order` to `OrderDetailsType`
**[VEN-1269](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1269):** Add is_application_order to OrderDetailsType
```shell
$ pytest payments/tests/test_payments_queries.py::test_get_order_status
```
> VEN-1269 | Add is_application_order to OrderDetails

- payments/models.py
- payments/schema/mutations.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations_update_offer.py
Added a UpdateBerthSwitchOfferMutation, which currently supports just changing the offer status and due_date (it's based on the corresponding UpdateOrderMutation so it was easiest to do this way).
**[VEN-1211](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1211):**
> VEN-1211: Mutation to cancel switch offer

- leases/schema/mutations.py
- leases/schema/utils.py
- leases/tests/test_lease_mutations.py
* Create boat when a lease is created
* Extract `lookup_boat` to a separate util to lookup or create the necessary boat
When a lease is being created for an application and no boat is passed, it creates a boat based on the information filled on the application. This is handled during the lease creation process, that way we ensure that we don’t end up creating unnecessary boats that will just clutter the system. If necessary, this can be refactored to create boats on other steps of the process.
**[VEN-1262](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1262):** Create boat during application processing
```shell
$ pytest leases/tests/test_lease_mutations.py
```
Create a lease for an existing application, check that the results are the expected:
```graphql
mutation CreateLease { …
```
> VEN-1262 | Create boat when a lease is created

- payments/schema/types.py
- payments/tests/test_payments_queries.py
**[VEN-1234](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1234): Differentiate between sent/unsent invoices**
```
pytest payments/tests/test_payments_queries.py::test_get_order_without_due_date
```
> VEN-1234 | Set OrderNode due date to optional

- payments/models.py
- payments/tests/test_payments_models.py
* Check if offer has lease before updating status
**[VEN-1289](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1289):** changing the status of order without lease
https://sentry.hel.ninja/aok/berth-api/issues/21242/
```shell
$ pytest payments/tests/test_payments_models.py::test_order_set_status_no_lease
```
> VEN-1289 | Check if offer has lease before updating status

- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
* UpdateOrderMutation is now more like ResendOrderMutation and ApproveOrderMutation, allowing multiple orders in input
**[VEN-1283(https://helsinkisolutionoffice.atlassian.net/browse/VEN-1283):**
> VEN-1283: modify UpdateOrderMutation to allow multiple Orders at a time

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- payments/utils.py
- templates/email/messages/berth_application_confirmation_en.html
- templates/email/messages/berth_application_confirmation_sv.html
- templates/email/messages/berth_none_offered_fi.html
- utils/messaging.py
Translate "drafted" status as "luotu"
Change the subtitle in the "berth rejected" email as follows:
Venepaikkahakemus käsitelty
Berth application processed
Ansökan om båtplats hanterat
Fix minor typo in a "berth rejected" email template
> Updated translations and "no berth" email template

- payments/models.py
There's actually another check in initiate_refund that comes to play before set_status is called, but let's fix it anyway.
**[VEN-1300](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1300):**
> VEN-1300: disallow setting status of paid_manually invoices to refunded

- resources/admin.py
- resources/schema/types.py
- resources/tests/test_resources_queries.py
Make isAvailable through graphql api
**[VEN-978](https://helsinkisolutionoffice.atlassian.net/browse/VEN-978):** 
resources/tests/test_resources_queries.py:test_get_winter_storage_places
resources/tests/test_resources_queries.py:test_get_winter_storage_place_with_leases
> VEN-978: add isAvailable to WinterStoragePlaceNode

- leases/tests/test_send_berth_invoice_service.py
- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform_refund.py
- payments/tests/test_payments_mutations_refunds.py
If refund `customer_email` does not exist, try to fetch the email from the related application `email` field.
-
```
pytest payments/tests/test_bambora_payform_refund.py::test_initiate_refund_no_order_email
pytest payments/tests/test_bambora_payform_refund.py::test_initiate_refund_no_order_email_or_application
```
> Get refund email from application

- customers/admin.py
- leases/admin.py
* Replace the default `select` for the inline lease forms with `select2` to avoid fetching all the winter places and sections for every instance of the lease
> Tech | Optimise inlines on CustomerProfile admin

- applications/models.py
- payments/models.py
- payments/schema/mutations.py
- payments/tests/test_payments_mutations_accept_berth_switch_offer.py
- payments/tests/test_payments_mutations_create_berth_switch_offer.py
- payments/tests/test_payments_mutations_send_berth_switch_offer.py
- payments/tests/test_payments_mutations_update_offer.py
- payments/utils.py
Set application status at these points in offer life cycle:
* offer rejected -> application rejected
* offer expired -> application expired
* After the Offer is generated -> the application is set to OFFER_GENERATED status.
* Offer never needs to enter ApplicationStatus.HANDLED state (which is rendered as "invoice paid" in the admin UI)
**[VEN-1304](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1304):**
> VEN-1304: update application status when switch offer status is updated

- applications/models.py
- applications/tests/test_application_models.py
* Add a `strip` for all the char fields on `applications`
**[VEN-1313](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1313):** Cleanup application data
```shell
$ pytest applications/tests/test_application_models.py::test_berth_application_stripped_fields
$ pytest applications/tests/test_application_models.py::test_winter_storage_application_stripped_fields
```
1. Create an application, either on the shell, Django Admin, or GQL API
2. Fill the char fields (e.g. names, email, address) with leading and/or trailing spaces
3. When the application is created, check that the values have been stripped
> VEN-1313 | Add cleanup for application CharFields

- payments/models.py
- payments/tests/test_payments_models.py
Since the lease will be terminated later, we only check that the lease
has been paid on the moment we create the offer. Otherwise, this blocks
updating the offer if at some point the lease status changes.
* Check that the lease is on `PAID` status only when it's created
* Check that the lease is on the current season only at the moment of creation
**[VEN-1317](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1317):** Allow cancelling offers for terminated leases
```shell
$ python payments/tests/test_payments_models.py::test_berth_switch_offer_lease_changed_status
```
> VEN-1317 | Only check for offer lease status when creating

- payments/schema/mutations.py
- payments/tests/test_payments_mutations_accept_berth_switch_offer.py
* Connect the switch application with the new lease
When the `switch offer` is accepted, the new lease is generated but it's not connected to the application. 
```shell
$ pytest payments/tests/test_payments_mutations_accept_berth_switch_offer.py::test_accept_offer
```
> Fix | Connect the switch application with the new lease

- payments/exceptions.py
- payments/providers/bambora_payform.py
- payments/tests/conftest.py
- payments/tests/test_bambora_payform_refund.py
- payments/tests/test_payments_mutations_refunds.py
- payments/utils.py
* Refactor refunding to replace amount for products
As per VismaPay support:
> _We checked some of your test refunds and noticed, that you are refunding with custom amount. With Helsingin kaupunki Liikuntapalvelu (931) merchant account you have to refund products, otherwise the accounting data will break._
**[VEN-1319](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1319):** Refund VismaPay by products
```shell
$ pytest payments/tests/test_bambora_payform_refund.py
$ pytest payments/tests/test_payments_mutations_refunds.py
```
TBD
> VEN-1319 | Refactor refunding to replace amount for products

- payments/providers/bambora_payform.py
- payments/tests/conftest.py
- payments/tests/test_bambora_payform_refund.py
* VismaPay sends the product price as string (not int), so cast it to int to operate properly
> VEN-1319 | Cast bambora product price to int

- applications/migrations/0028_replace_berth_switch_harbor_with_resources.py
- applications/migrations/0029_replace_harborchoice_harbors_with_resources.py
- applications/migrations/0031_replace_winterstorageareachoice_area_with_resources.py
- applications/migrations/0034_replace_berthswitch_harbor_for_berth.py
- scripts/delete_incomplete_switch_applications.py
During the process of removing the harbors app, some manual changes had to be made on the fly to complete the migration. This are the corresponding changes to the migrations and scripts.
**[VEN-1229](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1229)** 
#511 
The `scripts/delete_incomplete_switch_applications.py` has to be run _before_ the migration process starts, since later the changes to the model will block running it.
> VEN-1229 | Add changes to migrations made during the transition

- payments/admin.py
- payments/providers/bambora_payform.py
- payments/tests/test_bambora_payform_refund.py
* Make `OrderRefund.order` as `autocomplete_fields` to improve loading time
* Add `time_settled` to `OrderRefund` to see easily when the refund was settled
* Rename the `BamboraPaymentRefundDetails.id` to `refund_id` (as per VismaPay docs)
* Raise an error when creating a new refund if the order already has a pending refund
```shell
$ pytest payments/tests/test_bambora_payform_refund.py::test_initiate_refund_another_pending_refund
```
> Fix | Miscellaneous refund fixes

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
According to the [cronjob action documentation](https://github.com/City-of-Helsinki/setup-cronjob-action):
> **Name:** name
> **Description:** Name to use in job. Mandatory if multiple cronjobs in one namespace
> **Default:** `action-cronjob`
So we need to explicitly set the names to allow all jobs to run.
> Tech | Add names to order and offer cronjobs

- customers/services/profile.py
This avoids issues when comparing object id and one has str and other has UUID
> VEN-877: When creating CustomerProfile, use UUID object as the id

- applications/schema/types.py
- payments/schema/queries.py
- payments/schema/types.py
- payments/tests/test_payments_queries.py
Rename fields in OrderDetails to make them generic and let the frontend determine how to display them based on the order_type field.
**[VEN-1293](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1293):**
> VEN-1293/add winter storage place information to order details

- applications/tests/conftest.py
- payments/tests/test_payments_order_expiration.py
- payments/utils.py
* Set the correct expired status for "normal" applications when the order is expired
**[VEN-1352](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1352):** Set application to EXPIRED when the lease&invoice are expired
```shell
$ pytest payments/tests/test_payments_order_expiration.py::test_expire_too_old_unpaid_orders
```
Once the changes are released, the following script has to be run to expire the applications connected to already expired orders:
https://gist.github.com/a-rmz/92e0f90f1b89a33c90e026f4dfe9a872
> VEN-1352 | Expire all berth applications along with orders

- .prod/on_initialize.sh
- README.md
- resources/fixtures/helsinki-harbor-resources-fixes-2021-06-11.json
python manage.py loaddata helsinki-harbor-resources2
Changes agreed in meeting with admins: (sorry notes in Finnish only)
Merisatama
* Ehrenströmintie 21=rantamuuri erotetaan omaksi satamakseen ja muutetaan nimeksi "Ehrenströmintie ranta". ei porttia, vettä eikä sähköä.
Katajanokan venesatama
* Rantamuuri erotetaan omaksi "satamaksi" tietokannassa. Rantamuurin venepaikoissa ei porttia.
Kipparlahden venesatama
* Rantamuuri erotetaan omaksi "satamaksi" tietokannassa. Rantamuurin venepaikoissa ei porttia.
Laivalahden venesatama
* Reginankuja erotetaan omaksi "satamaksi" tietokannassa. Reginankujan venepaikoissa ei sähköä, porttia eikä jätehuoltoa.
* Aallonmurtaja erotetaan omaksi "satamaksi" tietokannassa. Aallonmurtajan venepaikoissa ei sähköä eikä porttia.
Merihaan venesatama
* Merihaassa …
> VEN-1342: split harbors with a new fixture

- resources/models.py
- resources/tests/test_resources_models.py
Fix berth is_available calculation when the summer season is ongoing
**[VEN-1358](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1358):** 
resources/tests/test_resources_models.py:test_berth_is_available_one_paid_lease
> VEN-1358: fix is_available calculation for berths

- applications/schema/mutations.py
- applications/schema/types.py
- applications/tests/test_applications_mutations.py
- berth_reservations/tests/conftest.py
- users/decorators.py
- users/tests/test_permission_utils.py
- users/utils.py
- utils/relay.py
* Add a decorator that allows checking for permissions for admins in case the user is an admin, or checking that the given nodes belong to the customer, in case the user is a customer
* Set the `DeleteBerthApplicationMutation` to use that check to allow customers deleting their own stuff
**[VEN-1222](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1222):** Mutation for canceling the application
```shell
$ pytest applications/tests/test_applications_mutations.py
```
> VEN-1222 | Mutation for deleting application

- berth_reservations/tests/conftest.py
- payments/schema/types.py
- payments/tests/test_payments_queries_berth_switch_offers.py
- resources/schema/utils.py
* Add checks for `BerthSwitchOfferNode` to allow only authorized users to query
**[VEN-1320](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1320):** Add permission checks to BerthSwitchOfferNode
```shell
$ pytest payments/tests/test_payments_queries_berth_switch_offers.py
```
> VEN-1320 | Add permission checks for BerthSwitchOffers

- applications/schema/types.py
- contracts/schema/types.py
- customers/schema/types.py
- leases/schema/types.py
- payments/schema/types.py
- utils/relay.py
* Add a util function to only return the resources that belong to the customer making the request
* Add the check for ownership to missing nodes and querysets
**[VEN-1245](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1245):** Add authorisation for customers
#540 
```shell
$ pytest
```
> VEN-1245 | Check owner permissions

- applications/schema/queries.py
- applications/tests/test_applications_berth_application_queries.py
- leases/schema/queries.py
- leases/tests/test_lease_queries.py
- payments/schema/types.py
- payments/tests/test_payments_queries.py
- payments/tests/test_payments_queries_berth_switch_offers.py
- utils/schema.py
* Remove additional permission checks for some nodes
Some nodes had additional `view` permission checking, which was not allowing for customers to query their own information. This permissions are already being checked on the `Node` level on the `get_queryset`method, so this extra checks were redundant.
**[VEN-1245](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1245):** Add authorisation for customers
#540 
#598 
1. Login as a non-admin user
2. Execute one of the fixed queries (leases, applications), you should see only the nodes that belong to the logged in user
```graphql
query BerthLeases {
berthLeases {
count
totalCount
edges {
node {
id
}
}
}
}
```
> VEN-1245 | Remove additional permission checks

- leases/models.py
- leases/tests/test_lease_queries.py
- resources/tests/test_resources_models.py
The logic for determining which leases are renewable for the next season worked on a way that on certain dates (like today - 16.8.21) it was getting the wrong season for renewing.
The updated logic checks:
* If today is during the season, get the leases which start on the `season_start.year`
* If today is outside of the season, get the leases which start on the previous year from the following season start (i.e. `season_start.year - 1`)
```
pytest leases/tests/test_lease_queries.py::test_query_send_marked_winter_storage_invoice_preview_2021_08_17
```
> Fix calculation for renewable marked winter places

- leases/services/invoice/base.py
* When creating the copy of the contract for the renewed lease, we keep the status so that customers that have signed the contract don't have to sign it again
> VEN-1368 | Keep the status of renewed leases

- resources/schema/queries.py
- resources/schema/types.py
* Add an `orderBy` option to the `harbors` query, which supports `name` (A-Z) and `-name` (Z-A)
* Set the default as A-Z
* Takes the language from the request, so it automatically sorts based on the language
**[VEN-1369](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1369):** Sort Harbors by name
```
query Leases {
harbors {
edges {
node {
properties {
name
}
}
}
}
}
```
> VEN-1369 | Add ordering by name for Harbors

- leases/models.py
- leases/tests/test_lease_mutations.py
- leases/utils.py
**[VEN-1394](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1394):** In admin UI it is not possible to terminate lease while season is over
```shell
$ pytest leases/tests/test_lease_mutations.py
```
> VEN-1394 | Fix end date calculation for terminated leases

- .github/workflows/review.yml
- .github/workflows/staging.yml
- README.md
Switch the staging and review environments to use Kanslia's test Tunnistamo and HKI Profile to be able to test Suomi.fi strong authentication.
**[VEN-1401](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1401)** 
It is not possible to fully test this before merging, but most parts can be tested locally. 
Currently it is not possible to get PR environments' authentication to actually work with Kanslia's Tunnistamo, but those envs are not working at the moment anyway, so we switch them to Kanslia's Tunnistamo to prevent confusion in the future.
> VEN-1401 | Use Kanslia's test Tunnistamo and HKI Profile in staging env

- customers/schema/mutations.py
- customers/services/profile.py
- customers/tests/test_customers_mutations.py
Fixed two issues related to `createMyBerthProfile` mutation:
* `myProfile` query to HKI profile which the mutation executes was broken.
* the mutation returned an error if the user already had a profile. Changed it to always return a valid `ProfileNode` and a boolean field `created` that tells if a new profile was created or not.
**[VEN-1416](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1416): createMyBerthProfile mutation call fails with unclear reason**
> VEN-1416 | Fix createMyBerthProfile mutation

- applications/schema/types.py
- berth_reservations/middlewares.py
- customers/schema/loaders.py
- resources/schema/__init__.py
- resources/schema/loaders.py
- utils/dataloaders.py
* Add an explicit resolver for Harbor/Area properties that are only annotated by the manager, so they have to be explicitly queried
**[VEN-1420](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1420):** Querying harbours through berthApplication results in an error
```graphql
query Applications {
berthApplications {
edges {
node {
id
harborChoices {
harbor {
id
properties {
name
electricity
gate
lighting
wasteCollection
water
}
}
}
}
}
}
}
```
Should then include the values for the selected harbor.
```json
{
"properties": {
"name": "Airorannan venesatama",
"electricity": false,
"gate": false,
"lighting": false,
"wasteCollection": false,
"water": false
}
}
```
> VEN-1420 | Resolve annotated props on single node calls

- .github/workflows/production.yml
- Dockerfile
* Replace the `ProfileService` url
* [2.0.12-hotfix](https://github.com/City-of-Helsinki/berth-reservations/releases/tag/release-2.0.12-hotfix)
This was already fixed as a hotfix on [2.0.12-hotfix](https://github.com/City-of-Helsinki/berth-reservations/releases/tag/release-2.0.12-hotfix), but this PR is to bring this changes properly to `master`
> Update Profile service API URL

- leases/tests/test_lease_mutations.py
- payments/models.py
- payments/tests/test_bambora_payform_refund.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations.py
- payments/tests/test_payments_mutations_refunds.py
Earlier marked winter storage order prices were rounded to the nearest one euro, now they are rounded to the nearest one cent.
**[VEN-1422](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1422): Price rounding wrong**
> VEN-1422 | Fix marked winter storage order price rounding

- payments/models.py
- payments/providers/talpa_ecom.py
- payments/tests/test_talpa_ecom.py
* Parse the `vatPercentage` as string
* Give higher priority to order customer fields rather than application
> VEN-1411 | Fix Order payload not built correctly

- payments/providers/talpa_ecom.py
- payments/tests/test_talpa_ecom.py
* Rename the `type` parameter to `eventType`
* Fix some more tests
> VEN-1411 | Rename event type param for webhook calls

- applications/migrations/0037_add_application_boat_relation.py
Now we use an existing boat only if the application has a related `CustomerProfile` instance and a `boat_registration_number`, and there is exactly one `Boat` that matches those.
Also, applications are now handled in creation order.
> Fix migration that populates boat for applications

- berth_reservations/settings.py
Otherwise the command's output is returned as bytes.
> Interpret git command output as text

- README.md
- docker-compose.yml
With the current default settings it was impossible to run berth-reservations along with tunnistamo and open-city-profile.
> Fix docker environment related conflicts

- Dockerfile
- applications/__init__.py
- berth_reservations/oidc.py
- berth_reservations/settings.py
- berth_reservations/urls.py
- contracts/__init__.py
- customers/__init__.py
- exports/apps.py
- exports/tests/conftest.py
- exports/tests/test_customer_export.py
- exports/urls.py
- exports/utils.py
- exports/views.py
- exports/xlsx_writer.py
- leases/__init__.py
- payments/__init__.py
- requirements-dev.txt
- requirements.in
- requirements.txt
- resources/__init__.py
- users/__init__.py
- users/tests/conftest.py
This PR adds initial excel export for customers, but also some general classes for adding more exporters later.
**[VEN-1444](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1444):** BE: API implements different Excel export views in their own endpoints
**[VEN-1434](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1434):** As an admin I can export a customer list to excel
Fetching user information from Helsinki profile backend using `ProfileService` coming later.
> VEN-1434 VEN-1444 | Admin can export a customer list to an excel

- customers/schema/queries.py
- customers/services/profile.py
- customers/tests/test_customers_queries.py
- payments/tests/test_talpa_ecom.py
- Merged two filters from HKI `profiles` query and Vene `berthProfiles` query
- Basically, when there is any HKI `profiles` filters (`HELSINKI_PROFILES_FILTERS `) used in the query, the API will ask for `apiToken`. Otherwise `apiToken` is not needed
- When `profiles` filter is used and `apiToken` is provided, Vene API will first send a GraphQL query to HKI profile GraphQL to get the ids of filtered `profiles` first. After that it'll filter Vene `berthProfiles` by these ids (because berthProfile ids are referred to HKI Profile ids)
**[VEN-1469](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1469):** 
- Tested in my local env with some simple query
```
query ProfileQuery($apiToken: String){
berthProfiles(lastName: "M", apiToken: $apiToken, sortBy: "name"){
edges{
node{
id
boats{ …
```
> Merge filters to berthProfiles

- applications/tests/test_applications_utils.py
- exports/tests/test_customer_export.py
- exports/views.py
- exports/xlsx_writer.py
- requirements-dev.in
- requirements-dev.txt
This PR adds Helsinki profile related information to the customer excel export.
Customer excel exporter view now requires a new `profile_token` (API key for the Helsinki profile GraphQL API) argument, which is used to fetch customer related information from Helsinki profile into the exported excel.
Additionally `xlrd` is changed to `openpyxl` since new versions of xlrd are only intended for reading old `.xls` files.
**[VEN-1465](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1465):** BE: backend resolves the names of the customer profile
> VEN-1465 | Customer excel export fetches information from Helsinki profile

- exports/tests/test_customer_export.py
- exports/views.py
GraphQL API uses the same formatting so this change unifies the external API.
> VEN-1450 | Use profileToken as export argument

- .pre-commit-config.yaml
- applications/schema/inputs.py
- applications/tests/test_applications_mutations.py
- berth_reservations/settings.py
- resources/schema/mutations.py
- utils/patch.py
- utils/tests/test_patch.py
This PR patches `graphene.Decimal.parse_value` with improved float handling. Also we replace all explicit Float types in mutation inputs.
**[VEN-1436](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1436):** BE: Unmarked winter storage notification has floats instead of decimals
**[VEN-533](https://helsinkisolutionoffice.atlassian.net/browse/VEN-533):** Backend: passing floats for DecimalFields does not always pass validation
> PT-1436 PT-533 | Patch graphene.Decimal

- payments/notifications/dummy_context.py
- templates/sms/berth_switch_notice_en.txt
- templates/sms/berth_switch_notice_fi.txt
- templates/sms/berth_switch_notice_sv.txt
Adds more information to the berth swtich offer SMS and updates the dummy context for the notification preview.
**[VEN-1462](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1462):** Addition to SMS berth offer notification
> VEN-1462 | Add information about the offered berth to the switch offer SMS

- berth_reservations/tests/factories.py
- leases/tests/test_send_berth_invoice_service.py
- payments/exceptions.py
- payments/utils.py
VEN-1175. Raise the InvoicingRejectedForPaperInvoiceCustomersError when payment notification is being sent to a paper customer. Catch the exception on order approving so the changes to the order are still persisted. Fixed the tests for paper invoice customer testing.
When the customer has selected paper invoicing, all the order handling should be done as when the invoicing type would be something else (only digital invoicing currently available), but the payment notification should not be sent, because a paper document should be used instead.
Investigation of the payment notification process is done in the Jira ticket comments: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1175?focusedCommentId=61250
> Reject payment notification sending when order has paper invoice customer

- payments/notifications/dummy_context.py
- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/tests/test_payments_mutations_approve_order.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/utils.py
- templates/sms/invoice_notice_en.txt
- templates/sms/invoice_notice_fi.txt
- templates/sms/invoice_notice_sv.txt
Berth information will be included in `SMS_INVOICE_NOTICE` notification if it's available.
**[VEN-1462](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1462):** Addition to SMS berth offer notification
> VEN-1462 | Include berth information in SMS

- customers/management/commands/fetch_customer_emails.py
- customers/services/profile.py
This PR adds a management command for fetching emails for a given list of profile ids from Helsinki profile. Also this fixes a bug where `ProfileService.get_all_profiles` ended up into an infinite query loop when fetching profiles without the `profile_ids` argument.
- **[VEN-1511](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1511)** 
./manage.py fetch_customer_emails --profile-token helsinki-profile-jwt-token-here --input-file customer_ids.txt --output-file customer_emails.csv
> VEN-1511 | Add management command for fetching customer email

- customers/schema/queries.py
- customers/tests/test_customers_queries.py
VEN-1481. The ids filter was denied by Open City Profile API, so it can be removed from Berth API. When resolving the berth profiles, first fetch all the profiles with given filters, then query from berth db. 
The Open city profile now responds with` 413 Request Entity Too Large` when there are ~3500 ids. This differs from what we have investigated when we implemented the current version of customer query.
> Remove ids filter from berth profiles query

- payments/management/commands/get_customer_emails.py
- payments/tests/conftest.py
- payments/tests/test_get_customer_emails_command.py
get_customer_emails management command help:
- usage: manage.py get_customer_emails
[-h] [--year Y] [--month M] [--day D] [--encoding E]
[--exclude-berth-orders] [--exclude-winter-storage-orders]
[--use-posix-line-separator]
"Get customer emails from berth and winter storage orders active on
given date \<TODAY\> and save them to customer_emails_\<TODAY\>.txt.
TODAY is determined by the parameters YEAR, MONTH and DAY.
Emails are included from berth orders (venepaikkatilaukset) created
between June 10 – June 9 next year for such a time period which
contains \<TODAY\>.
Emails are included from winter storage orders (talvisäilytystilaukset)
created between September 15 – June 9 next year for such a time period
which contains \<TODAY\>." …
> VEN-1524 | Add management command get_customer_emails & tests

- payments/management/commands/get_customer_emails.py
- payments/tests/test_get_customer_emails_command.py
Update the get_customer_emails management command's date ranges for the
berth orders and winter storage orders based on discussion with the
Venepaikka / berth reservations service's product owner:
- **Berth orders'** date range changed (**DAY/MONTH** format):
- Old range: 10/6 – 9/6
- New range: **1/12 – 14/9**
- **Winter storage orders'** date range changed (**DAY/MONTH** format):
- Old range: 15/9 – 9/6
- New range: **1/8 – 9/6**
The orders are not filtered by status at the moment and for the current
use case that should be fine although it may produce false positives.
For the service's product owner this was fine for the moment.
The current help text for get_customer_emails management command:
```
usage: manage.py get_customer_emails
[-h] [--year Y] [--month M] [--day D] [--encoding E] …
```
> VEN-1524 | Update get_customer_emails command's order date ranges

- berth_reservations/settings.py
Reminder cronjob has failed on Platta because it could not write mailer lock file to /app -directory.
Use variable MAILER_LOCK_PATH to write mailer lock file to /tmp -directory.
**[VPLAENH-546](https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-546):**
> mailer lockfile to tmp directory PLAENH-546

- Dockerfile
- docker-compose.yml
- docker/postgres/Dockerfile
- setup_user.sh
fixes:
- building docker containers reliably with the recent docker hub rate
limits (i.e. by not using docker hub's images we don't need to worry
about their rate limiting)
also:
- remove deprecated version number from docker-compose.yml
- use new style ENV settings in Dockerfiles i.e. `ENV VAR=VAL` instead
of old style `ENV VAR VAL`
- remove SonarCloud code smells from Dockerfiles
- docker:S6587: "Cache should be cleaned after package installation"
- https://rules.sonarsource.com/docker/RSPEC-6587/
- docker:S7018: "Arguments in long RUN instructions should be sorted"
- https://rules.sonarsource.com/docker/RSPEC-7018/
- docker:S7031: "Reduce the amount of consecutive RUN instructions"
- https://rules.sonarsource.com/docker/RSPEC-7031/
refs VEN-1577 …
> VEN-1577 | fix(docker): use Amazon ECR as source, remove helsinkitest

- customers/tests/test_gdpr_api.py
- exports/tests/test_winter_storage_application_export.py
- leases/tests/test_send_berth_invoice_service.py
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- payments/models.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations_approve_order.py
fixes running tests locally, in the CI/CD pipeline there were
environment variables set in a specific way that the tests passed there
also:
- fix incorrect VAT percentage translation using `€` instead of `%`
refs VEN-1575
**[VEN-XXX](https://helsinkisolutionoffice.atlassian.net/browse/VEN-XXX):** 
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEN-1575 | fix(tests): set OIDC settings, mock SMS sending, fix translation use

- berth_reservations/tests/utils.py
- customers/tests/conftest.py
- customers/tests/test_sms_notification_service.py
- payments/providers/talpa_ecom.py
- payments/tests/conftest.py
- payments/tests/test_bambora_payform_refund.py
- payments/tests/test_talpa_ecom.py
TalpaEComPaymentDetails total_excl_tax, total and tax_amount fields were
incorrectly handled before, they were not integer values but were
handled as integer values. Now parsing the incoming JSON data which is
encoded as text, so that the floating point values that haven't yet been
decoded to floating point values but are still represented as text are
actually parsed as Python's Decimal instances to retain their accurate
values exactly.
refs VEN-1575
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEN-1575 | fix: TalpaEComPaymentDetails int -> Decimal price/tax fields

- templates/email/messages/berth_invoice_en.html
- templates/email/messages/berth_invoice_fi.html
- templates/email/messages/berth_invoice_sv.html
- templates/email/messages/berth_offer_new_en.html
- templates/email/messages/berth_offer_new_fi.html
- templates/email/messages/berth_offer_new_sv.html
- templates/email/messages/berth_offer_switch_en.html
- templates/email/messages/berth_offer_switch_fi.html
- templates/email/messages/berth_offer_switch_sv.html
refs VEN-1589
**[VEN-1589](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1589):** 
VEN-1589
[VEN-1589]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken links in backend email templates

- .prod/uwsgi.ini
VEN-1584.
Keycloak will include so many ad-groups in the JWT that the request buffers-size needs to be increased. Set a consistent value copied from Kukkuu.
> fix: increase uwsgi buffer-size
