- berth_reservations/settings.py
- berth_reservations/urls.py
- reservations/api.py
> Add reservation creation endpoint

- reservations/admin.py
- reservations/utils.py
> Add admin action to export reservations to CSV file

- harbors/management/commands/create_harbors_from_json.py
- harbors/management/commands/update_harbors_from_servicemap.py
- parse_harbors_csv.py
> Add commands for creating / updating Harbors

- harbors/fixtures/helsinki-harbors.json
New harbors added and old harbors edited per new specs.
> Update Helsinki harbors' data fixture

- reservations/admin.py
Disallow deleting reservations from the admin panel.
> Do not allow deleting reservations

- reservations/utils.py
Add column with reservations' creation timestamps
to CSV export file.
> Add creation timestamp to reservations CSV

- berth_reservations/settings.py
Add extra configuration parameters.
> Update mailgun integration

- berth_reservations/tests/conftest.py
- harbors/tests/conftest.py
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
- reservations/admin.py
- reservations/tests/conftest.py
- reservations/tests/factories.py
- reservations/tests/test_reservations_admin.py
- reservations/tests/test_reservations_utils.py
- reservations/utils.py
More user friendly than CSV.
Closes #49
> Export reservations to an xlsx file

- berth_reservations/schema.py
- berth_reservations/settings.py
- berth_reservations/urls.py
- harbors/schema.py
- harbors/tests/conftest.py
- harbors/tests/test_harbors_graphql.py
- requirements.in
- requirements.txt
- reservations/schema.py
- reservations/tests/test_reservations_graphql.py
> Adds Graphql

- harbors/schema.py
> Handle no image files in GraphQL Harbors query

- reservations/admin.py
> Add berth switch fields to admin

- harbors/fixtures/helsinki-harbors.json
Identifier field was deleted from all models.
> Update harbors fixtures to not have identifier fields

- reservations/schema.py
We had the same notification signal in REST API logic.
> Send notification on creating reservation through GraphQL

- .travis.yml
- docker/postgres/Dockerfile
- requirements.txt
This will fix security vulnerabilities.
> Upgrade requirements to newer versions

- reservations/admin.py
- reservations/tests/conftest.py
- reservations/tests/factories.py
- reservations/tests/test_reservations_utils.py
- reservations/utils.py
1. Register winter reservations with django admin.
2. Update excel export logic to cover winter reservations too.
3. Update excel export logic to include berth switch info.
Refs VEN-55, VEN-56
> Update django admin logic for winter reserv. and berth switches

- reservations/enums.py
Add 'under a tarp' to storage method enum for winter reservations.
> Add another winter storage method to the enum

- .travis.yml
- berth_reservations/tests/conftest.py
- requirements.txt
- reservations/apps.py
- reservations/migrations/0013_copy_templates.py
- reservations/notifications.py
- reservations/signals.py
- reservations/tests/factories.py
- reservations/tests/test_reservations_notifications.py
Fix signal for sending reservation notifications.
Refs VEN-145
> VEN-145 | Fix notifications

- customers/locale/fi_FI/LC_MESSAGES/django.po
- docker/django/Dockerfile
- resources/locale/fi_FI/LC_MESSAGES/django.po
1. Add gettext to Docker image
2. Add translations files
Translations were provided long time ago. 🙂
> VEN-346 | Translate mooring types

- berth_reservations/exceptions.py
- berth_reservations/schema.py
- berth_reservations/tests/conftest.py
- berth_reservations/tests/factories.py
- berth_reservations/tests/utils.py
- resources/schema.py
- resources/tests/conftest.py
- resources/tests/factories.py
- resources/tests/test_resources_mutations.py
* Add create, update, and delete mutations for `Berth`s.
* Add a test suite for the mutations
* Override `NOTIFICATIONS_ENABLED` on the test settings to avoid tests failing if the `.env` is missing.
Partially closes [VEN-143](https://helsinkisolutionoffice.atlassian.net/browse/VEN-143)
> VEN-143 | Berth mutations

- .pre-commit-config.yaml
- berth_reservations/tests/conftest.py
- berth_reservations/tests/factories.py
- berth_reservations/tests/utils.py
- requirements-dev.in
- requirements-dev.txt
- requirements.txt
- resources/schema.py
- resources/tests/conftest.py
- resources/tests/factories.py
- resources/tests/test_resources_mutations.py
* Add mutation and tests for the `Harbor` resource.
Partially closes VEN-143
To manually test the mutations, you can run the following queries on GraphiQL with the inputs provided. Just add valid IDs and you're ready to test. :rocket:
```graphql
query FetchHarbor($fetchId: ID!) {
harbor(id: $fetchId) {
id
type
geometry {
type
coordinates
}
bbox
properties {
name
servicemapId
streetAddress
zipCode
phone
email
wwwUrl
imageLink
municipality
imageFile
availabilityLevel {
title
}
numberOfPlaces
maximumWidth
maximumLength
maximumDepth
}
}
}
mutation CreateHarbor($createHarbor:CreateHarborMutationInput!) {
createHarbor(input:$createHarbor) {
harbor {
id
type
geometry {
type
coordinates
}
bbox
properties {
name
servicemapId
streetAddress
zipCode
phone
email
wwwUrl
imageLink
municipality
imageFile …
```
> VEN-143 | Harbor mutations

- resources/schema.py
- resources/tests/test_resources_mutations.py
* Add mutation and tests for the `Pier` resource.
Partially closes VEN-143
To manually test the mutations, you can run the following queries on GraphiQL with the inputs provided. Just add valid IDs and you're ready to test. :rocket:
```graphql
query FetchPier($fetchId: ID!) {
pier(id: $fetchId) {
id
properties {
harbor {
id
properties {
name
}
}
identifier
electricity
gate
lighting
mooring
water
wasteCollection
suitableBoatTypes {
id
name
}
}
}
}
mutation CreatePier($createInput: CreatePierMutationInput!) {
createPier(input: $createInput) {
pier {
id
properties {
harbor {
id
}
identifier
electricity
gate
lighting
mooring
water
wasteCollection
suitableBoatTypes {
id
}
}
}
}
}
mutation UpdatePier($updateInput: UpdatePierMutationInput!) {
updatePier(input: $updateInput) {
pier {
id …
```
> VEN-143 | Pier mutations

- applications/schema.py
This will disallow querying applications from this ObjectType.
> Hide applications from berth switch GQL type

- applications/tests/conftest.py
- applications/tests/test_reservations_utils.py
- applications/utils.py
Add a `Switch reason` column.
* If the application is a `switch application`, the column should have the finnish text for the reason or `"---"` if no reason.
* If it's a regular application, the column is just empty
Add columns `Copmany name` and `Business ID`.
* If those values were given, they are added
* Otherwise leave the cells empty
Closes [VEN-442](https://helsinkisolutionoffice.atlassian.net/browse/VEN-442)
**Berth Applications**
**Winter Storage Applications**
> [VEN-442] Export applications to Excel

- resources/schema.py
As per graphene docs, the kwargs param in mutate_and_get_payload
should have input instead of kwargs.
> Refactor mutations for resources

- resources/migrations/0003_replace_abstractplacetype_units.py
Apparently, there were some problems converting some of the existing data to the decimal, so this new migration should cover the cases for big numbers.
> Hotfix: Fix migration script

- resources/schema.py
* Add `min width` and `min length` filters to `BerthNode`
* Add `min berth width` and `min berth length` to `piers` query and `piers` field in `harbors` and `harbor_by_servicemap_id` query
* Add an explanation/warning to the `piers` query regarding which filter to use
* Add a private `_resolve_piers` function that does all the heavylifting for the filtering for piers
Closes [VEN-447](https://helsinkisolutionoffice.atlassian.net/browse/VEN-447)
```graphql
query Berths {
piers {
edges {
node {
id
properties {
berths(minWidth: 7, minLength: 10) {
edges {
node {
id
berthType {
id
width
length
}
}
}
}
}
}
}
}
}
query Piers {
piers(minBerthWidth: 5, minBerthLength: 10) {
edges {
node {
id
properties {
berths {
edges {
node {
id
berthType {
id
width
length
}
}
}
}
}
}
}
}
}
query ByServicemapID …
```
> VEN-447 | Dimension filters for Piers & Berths

- leases/tests/test_lease_queries.py
- resources/tests/test_resources_mutations.py
> Fix query and mutation indents to 4 spaces

- applications/new_schema.py
The model field could not be null either.
> Mark status field of BerthApplicationNode as non-nullable

- applications/fixtures/switch-reasons.json
App was renamed from "reservation"s to "applications".
> Update applications app's fixtures

- resources/signals.py
> Catch error raised when trying to remove files from filesystem

- resources/schema.py
- resources/tests/test_resources_mutations.py
* Raise an error when a resource (`Harbor`, `Pier`, or `Berth`) associated to a Lease is being deleted
* _Only_ raises the error when the Lease has a `PAID` status
* If the resource has associated resources but neither is `PAID`, the leases associated to the resource will be deleted, and then the resource.
**[VEN-478](https://helsinkisolutionoffice.atlassian.net/browse/VEN-478):** Do not allow deleting resources if they have connected active leases
```shell
$ pytest resources/tests/test_resources_mutations.py::test_delete_harbor_protected_with_lease
$ pytest resources/tests/test_resources_mutations.py::test_delete_pier_protected_with_lease
$ pytest resources/tests/test_resources_mutations.py::test_delete_berth_protected_with_lease
```
1. Create a Berth Lease
2. Set the status as `PAID`
3. …
> VEN-478 | Block resources associated to leases from deletion

- resources/schema.py
- resources/tests/test_resources_mutations.py
- Move most fields to common `BerthInput` class
- Change `create/update` mutations to accept either a `berth_type_id` or `width, length, berth_mooring_type` 
- If the `berth_type_id` is passed, it uses that one
- If dimensions are passed, it `get_or_create`s a suitable `BerthType`
- If _both_ are passed, it raises an error
- If only dimensions are passed but there's one missing, it raises an error
**[VEN-563](https://helsinkisolutionoffice.atlassian.net/browse/VEN-563):** Do not expect BerthType id in create/update mutations for BerthNode
```shell
$ python resources/tests/test_resources_mutations.py
```
```graphql
mutation UPDATE_BERTH($input: UpdateBerthMutationInput!) {
updateBerth(input: $input) {
berth {
id
berthType {
id
width
length
mooringType
}
}
}
}
```
```json
{
"input": { …
```
> VEN-563 | BerthType on Berth mutations

- customers/admin.py
**[VEN-592](https://helsinkisolutionoffice.atlassian.net/browse/VEN-592):** Add boat certificates to django admin
> VEN-592 | Expose BoatCertificate on admin

- leases/models.py
The previous PR (#223) added the `order` prop to `BerthLeases` so the API would work, but it didn't include `WinterStorageLeases`. They _do_ have models but are not yet implemented in the API. To avoid the same conflict in the future, the `order` prop has been added to all `AbstractLease`s.
**[VEN-398](https://helsinkisolutionoffice.atlassian.net/browse/VEN-398)** 
```shell
$ pytest
```
```python
In [1]: from leases.models import BerthLease, WinterStorageLease
In [2]: wsl = WinterStorageLease.objects.first()
In [3]: wsl.order
Out [3]: # ... WSL Order info
In [4]: bl = BerthLease.objects.first()
In [5]: bl.order
Out[5]: <Order: Smol berths (c7228358-e6e1-4033-8ebc-986a6e23b96a) - None (100.00€) [Waiting]>
```
> [Hotfix] VEN-398 | Resolve order for all abstract leases

- resources/schema.py
- resources/tests/test_resources_queries.py
* Expose the `leases` field on `WinterStoragePlaceNode` for consistency with `BerthNode`
**[VEN-671](https://helsinkisolutionoffice.atlassian.net/browse/VEN-671):**  #235 
```shell
$ pytest resources/tests/test_resources_queries.py::test_get_winter_storage_place_with_leases
$ pytest resources/tests/test_resources_queries.py::test_get_winter_storage_place_with_leases_not_enough_permissions
```
With an authorized user, execute the following query:
```graphql
{
winterStoragePlaces {
leases {
edges {
node {
id
}
}
}
}
}
```
> VEN-671 | Hotfix | Add leases to winter storage place node

- harbors/schema.py
* Add a resolver for `suitable_boat_types` on the "old" `Harbor` type
**[VEN-794](https://helsinkisolutionoffice.atlassian.net/browse/VEN-794):** BoatTypesBerthsQuery fails on test api
Execute the query shown on the [issue](https://venepaikka-api.test.hel.ninja/graphql/#operationName=BoatTypesBerthsQuery&query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20st …
> [VEN-794] Add resolver for old Harbor suitable boat types

- resources/management/commands/generate_winter_places.py
- resources/tests/test_resources_commands.py
Update the script that imports `WinterStoragePlace`s based on the spreadsheet on the ticket's attachments
**[VEN-605](https://helsinkisolutionoffice.atlassian.net/browse/VEN-605):** update WS places generating script
```shell
$ python resources/tests/test_resources_commands.py
```
1. Run the command
```
$ python manage.py generate_winter_places
```
2. Check the [`resources/winterstorageplace`](http://localhost:8000/admin/resources/winterstorageplace/)
> VEN-605 | Update WSPlace generate script

- berth_reservations/settings.py
- requirements.in
- requirements.txt
Will be used to debug performance using Elastic APM tools.
> Add Elastic APM debug configuration

- customers/models.py
- customers/tests/test_customer_models.py
- harbors/fixtures/helsinki-winter-areas.json
- resources/fixtures/helsinki-harbor-resources.json
* Update resource fixtures to add missing berths
* Catch missing berths to avoid creating leases
* Remove unmarked ws places from Lähteelä
**[VEN-630](https://helsinkisolutionoffice.atlassian.net/browse/VEN-630)** 
#289 
```shell
$ pytest customers/tests/test_customer_models.py
```
> Hotfix | VEN-630 | Timmi import

- payments/models.py
- payments/tests/test_bambora_payform.py
- payments/utils.py
Set application status to HANDLED when order is paid.
**[VEN-840](https://helsinkisolutionoffice.atlassian.net/browse/VEN-840)** 
`payments/tests/test_bambora_payform.py::test_handle_success_request_success`
> VEN-840 | Set application status to HANDLED when order is paid

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
* Add the Finnish 🇫🇮  and Swedish 🇸🇪 translations for the Django Admin
**[VEN-871](https://helsinkisolutionoffice.atlassian.net/browse/VEN-871):** Add translations to Django Admin
When the PR is merged, it's required to run:
```
$ python manage.py compilemessages -l fi -l sv
```
Should that be added to the build process maybe?
> Add new translations

- payments/admin.py
* Add `OrderToken`s to the Django Admin
> Add OrderToken to admin

- .gitlab-ci.yaml
Fix nasty typos in gitlab-ci config.
> Fix gitlab-ci file typos

- .gitlab-ci.yaml
Fix more typos in gitlab config.
> Fix more typos in gitlab-ci config file

- resources/fixtures/helsinki-ws-resources.json
> Pre-release rel/2020-10-15.1

- leases/admin.py
* For leases, check that the lease has an application, otherwise, show an empty placeholder
**[VEN-875](https://helsinkisolutionoffice.atlassian.net/browse/VEN-875)** 
#332
> VEN-875 | Hotfix | Check for lease application

- payments/providers/bambora_payform.py
- payments/tests/test_payments_mutations.py
* Exclude empty tokens when handling the `initiate_payment` flow
If the response from bambora was failing (either a `PayloadValidation` or service error), the token was saved as-is, so with a blank token value. When the client tried to get the payment link again, it would find that it had a valid token and return that URL to the user, however the token was empty and that’s why it was failing.
**[VEN-922](https://helsinkisolutionoffice.atlassian.net/browse/VEN-922)** 
```shell
$ pytest payments/tests/test_payments_mutations.py::test_payment_fails_doesnt_use_empty_token
```
> VEN-922 | Ignore empty OrderTokens when building the payment URL

- .prod/on_deploy.sh
- leases/management/commands/assign_ws_lease_stickers.py
- Create command for assigning stickers for existing paid WS leases
**[VEN-940](https://helsinkisolutionoffice.atlassian.net/browse/VEN-940)** 
./manage.py assign_ws_lease_stickers
> Create command for assigning stickers for existing paid WS leases

- .gitlab-ci.yml
- leases/admin.py
- Let staging environment to be built from master
> VEN-960 | Switch to GH flow

- resources/admin.py
- resources/models.py
* Add a private annotated field to provide proper ordering for numbers
* Add more details to django admin
**[VEN-848](https://helsinkisolutionoffice.atlassian.net/browse/VEN-848):** Berth number order
**[VEN-972](https://helsinkisolutionoffice.atlassian.net/browse/VEN-972):** Add search and filters for Resources on django admin
**Berth order number:**
1. Go to the django admin berths `resources/berth/`
2. You should see that the places are ordered correctly
**Django admin details:**
1. Check the berth, pier, harbor, ws place, ws section, and ws area pages
> VEN-848 | Berth number ordering

- payments/schema/mutations.py
Fix CreateAdditionalProductOrderMutation return type.
**[VEN-925](https://helsinkisolutionoffice.atlassian.net/browse/VEN-925)**
> VEN-925 | Fix CreateAdditionalProductOrderMutation return type

- templates/email/base_template_en.html
- templates/email/base_template_fi.html
- templates/email/base_template_sv.html
* Add email base templates (with Finnish, Swedish and English versions)
**[VEN-997](https://helsinkisolutionoffice.atlassian.net/browse/VEN-997):** Convert email templates to a more plain solution
> VEN-997 | Add email base templates

- customers/services/profile.py
- customers/tests/conftest.py
- customers/tests/test_profile_service.py
- payments/models.py
- payments/notifications/dummy_context.py
- payments/notifications/types.py
- payments/schema/mutations.py
- payments/tests/conftest.py
- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/tests/test_payments_order_types.py
- payments/utils.py
Approve order changes for AP order
- Do not update lease and applications status
- Send notification
Other
- Resolve lease order type as INVALID for AP order
- Extend hki profile with address info
- Minor fixes
**[VEN-1016](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1016)**
Several new tests in `payments/tests`
> VEN-1016 | Additional product order adjustments

- README.md
**[VEN-707](https://helsinkisolutionoffice.atlassian.net/browse/VEN-707):**
> add note about geospatial libraries to README.md

- payments/notifications/dummy_context.py
- templates/email/messages/additional_service_invoice_fi.html
Fix additional product order template due date.
> VEN-1016| Fix template due date

- payments/models.py
- payments/tests/test_payments_models.py
On the previous pricing schema, the fixed additional services
(electricity, gate, lighting, mooring, waste collection, and water) were
billed separately but the order lines were generated automatically when
creating the order, based on the services available on the pier/harbor.
The new pricing schema already includes those services on the berth
prices, so we don't need to bill them separately.
* Remove the `create_order_lines` from `Order` and the related tests.
**[VEN-964](https://helsinkisolutionoffice.atlassian.net/browse/VEN-964):** Update the pricing models
**#385** 
```shell
$ pytest payments/tests/test_payments_models.py
```
> VEN-964 | Remove automatic creation of order lines

- .prod/on_deploy.sh
- leases/notifications/__init__.py
- leases/notifications/dummy_context.py
- leases/notifications/types.py
- leases/schema/mutations.py
- leases/schema/types.py
- leases/services/invoice.py
- leases/tests/test_lease_mutations_send_invoices.py
- leases/tests/test_send_berth_invoice_service.py
- locale/fi/LC_MESSAGES/django.po
- scripts/load_notification_templates.py
- templates/email/messages/automatic_invoicing_email_admins_en.html
- templates/email/messages/automatic_invoicing_email_admins_fi.html
- templates/email/plain_messages/automatic_invoicing_email_admins_en.txt
- templates/email/plain_messages/automatic_invoicing_email_admins_fi.txt
**[VEN-843](https://helsinkisolutionoffice.atlassian.net/browse/VEN-843)** 
TBD
The tests still have to be fixed
> VEN-843 | Invoicing threaded

- leases/services/invoice.py
* `lease` does not have an updatable `contract` field
* Catch for errors when creating the new lease to add them to the failed leases
> HOTFIX | Remove invalid lease contract update

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- payments/models.py
- payments/notifications/dummy_context.py
- payments/tests/factories.py
- payments/utils.py
- templates/email/messages/berth_invoice_en.html
- templates/email/messages/berth_invoice_fi.html
- templates/email/messages/berth_invoice_sv.html
- templates/email/messages/berth_offer_new_en.html
- templates/email/messages/berth_offer_new_fi.html
- templates/email/messages/berth_offer_new_sv.html
- templates/email/plain_messages/berth_invoice_en.txt
- templates/email/plain_messages/berth_invoice_fi.txt
- templates/email/plain_messages/berth_invoice_sv.txt
* Add VAT to berth invoices
* Fix subject for berth emails
> Hotfix| Email subjects

- leases/services/invoice.py
> send invoicing notification email to everyone in "Berth services" group

- leases/models.py
- leases/tests/test_lease_queries.py
* Add a check to only renew leases with contracts
> HOTFIX | Only invoice leases with contracts

- .prod/on_deploy.sh
* Remove commands that don't need to be run anymore
> HOTFIX | Remove commands that don't need to be run anymore

- scripts/create_dummy_profiles_json.py
> set order created_at to a a date <= season end in dummy profiles

- berth_reservations/logging.py
- berth_reservations/settings.py
- requirements.in
- requirements.txt
For better visibility on logs, the new logger dumps the request-related logs as json so it can be parsed by the log aggregation services. It also adds more details to the log.
> Add custom logger for requests

- applications/new_schema/types.py
- customers/schema/types.py
- leases/schema/queries.py
- requirements.txt
- resources/tests/factories.py
- resources/tests/test_resources_mutations.py
* The latest version of `graphene-django` adds an `offset` parameter to node connections that could be useful for optimising bulky requests
> Tech | Bump graphene-django version

- berth_reservations/settings.py
* Prepend the `FORCE_SCRIPT` to the ignored paths for logging
> HOTFIX | Prepend FORCE_SCRIPT to ignored request paths

- payments/schema/types.py
* Add rejected_at field to node (and descriptions)
#435
> HOTFIX | VEN-1069 | Add rejected_at field

- .github/workflows/production.yml
> Add additional hostnames block

- resources/schema/types.py
> restore non-null to suitableBoatTypes and berths in graphql schema

- locale/sv/LC_MESSAGES/django.po
- templates/email/messages/additional_service_invoice_en.html
- templates/email/messages/additional_service_invoice_sv.html
- templates/email/messages/berth_none_offered_en.html
- templates/email/messages/berth_none_offered_sv.html
- templates/email/messages/general_cancel_confirmation_en.html
- templates/email/messages/general_cancel_confirmation_sv.html
Added translations for
* Additional service invoice
* No berth offered
* General cancel confirmation
**[VEN-981](https://helsinkisolutionoffice.atlassian.net/browse/VEN-981): Create email template for additional service invoice**
> Add email translations

- .gitignore
- leases/models.py
- payments/models.py
- payments/schema/mutations.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/utils.py
- utils/debug_util.py
**[VEN-1068](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1068):** 
**[VEN-950](https://helsinkisolutionoffice.atlassian.net/browse/VEN-950):**
> Feature/resend orders mutation (VEN-1068, VEN-950)

- payments/schema/mutations.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/utils.py
**[VEN-1068](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1068):**
> use profile_token to fetch customer info when available

- leases/services/invoice.py
* Before sending batch invoices, attempt re-sending the failed invoices
* Clears the status from orders/leases
* Updates the `order.customer_*`
* Re-sends the invoice
**[VEN-1071](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1071):** Admins can't send fixed invoices
#455 
1. Set an order and the lease to `ERROR` states
2. Call the `sendExistingBerthInvoices` mutation
```graphql
mutation SendFailed($send: SendExistingBerthInvoicesMutationInput!) {
sendExistingBerthInvoices(input: $input){
ok
}
}
```
```json
{
"input": {
"profileToken": "<profile token from Admin UI>"
}
}
```
3. The email should be printed on the console
4. Check the new status of the order
```graphql
query Orders {
order(id: "<order id>") {
status
lease {
... on BerthLeaseNode {
status
}
}
}
}
```
This PR …
> VEN-1071 | Resend batch error invoices

- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/tests/test_payments_mutations_approve_order.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/utils.py
- requirements.in
- requirements.txt
* For better UX, localise the due date based on the message language
#462
> HOTFIX | VEN-1126 | Localise the due date on the SMS

- .github/workflows/review.yml
**[VEN-1076](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1076):**
> use dynamic secret_name in cronjob review env config

- berth_reservations/tests/conftest.py
- payments/notifications/dummy_context.py
- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
- payments/utils.py
- templates/email/messages/order_cancelled_en.html
- templates/email/messages/order_cancelled_fi.html
- templates/email/messages/order_cancelled_sv.html
**[VEN-1063](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1063):**
> fix expired_at in cancellation email

- payments/models.py
- payments/tests/test_payments_models.py
- payments/tests/test_payments_mutations.py
- payments/utils.py
**[VEN-951](https://helsinkisolutionoffice.atlassian.net/browse/VEN-951):**
> VEN-951: set order status as cancelled

- payments/models.py
…be calculated
**[VEN-1131](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1131):**
> VEN-1131: better error message when "store on ice" invoicing fails

- leases/services/invoice.py
- leases/tests/test_send_berth_invoice_service.py
**[VEN-1060](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1060):**
> VEN-1060: fix fr failed_orders calculation

- templates/email/messages/order_refunded_confirmation_en.html
- templates/email/messages/order_refunded_confirmation_fi.html
- templates/email/messages/order_refunded_confirmation_sv.html
* Add "payment refunded" email templates
**[VEN-1199](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1199):** Email: Refund notification
> VEN-1199 | Add "payment refunded" email templates

- .github/workflows/production.yml
> enable order expiration cronjob in production environment

- leases/schema/mutations.py
- leases/tests/test_lease_mutations.py
**[VEN-1119](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1119):**
> VEN-1119: create lease without application

- leases/schema/mutations.py
- leases/tests/test_lease_mutations.py
- leases/utils.py
Add SwitchBerthMutation that allows to switch the berth from a berth lease to another berth that is not linked to a lease. The
berth lease must have a contract and the status must be paid in order to switch the berth for it.
In practice the old berth lease is terminated and a new one is created with the same information as the old one except with the berth changed to the new provided berth.
- Slight refactor of lease termination notification sending.
**[VEN-1191](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1191)** 
```
pytest leases/tests/test_lease_mutations.py::test_switch_berth
pytest leases/tests/test_lease_mutations.py::test_switch_berth_with_switch_date
pytest leases/tests/test_lease_mutations.py::test_switch_berth_without_contract
pytest …
```
> VEN-1191 | Change berth for a customer

- leases/consts.py
- leases/schema/mutations.py
- leases/tests/conftest.py
- leases/tests/test_lease_mutations.py
- leases/utils.py
**[VEN-1214](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1214):**
> VEN-1214: allow termination of leases in error and offered status

- harbors/admin.py
- harbors/fixtures/helsinki-harbors.json
- harbors/management/commands/harbors_connect_to_resources.py
- Disable old Hietalahdenallas (Jätkäsaaren puoli)
- Map Pajalahden venesatama (rantamuuri) with pier 19B
> Tech | Map resources to harbors (fixes)

- requirements.in
- requirements.txt
NOTE: Major version upgrade to Pillow. We are not using any pillow functionality directly. Is it only used for the defunct map file upload?
> Security upgrades to django, djangorestframework, jinja2, pillow

- .prod/on_deploy.sh
- requirements-dev.txt
- requirements.txt
> Security upgrade: pyyaml 5.3.1->5.4.1

- resources/schema/utils.py
- resources/tests/test_resources_queries.py
**[VEN-1254](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1254):**
> VEN-1254: fix error when only minBerthWidth or minBerthLength is included in query

- payments/providers/bambora_payform.py
* Terminate the lease when the refund is the full amount
**[VEN-1159](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1159)** 
#485 
#499 
#514
> VEN-1159 | Terminate the lease when the refund is the full amount

- berth_reservations/settings.py
* Add the missing required variable
> VEN-1208 | Add missing number of days to expire offers

- .prod/on_deploy.sh
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
- resources/tests/factories.py
In case of new models or updated permissions, run the `set_group_model_permissions` script on deploy so that groups get the updated permissions.
**[VEN-1216](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1216): Query for the customer personal information**
> VEN-1216 | Update group permissions on deploy

- payments/tests/test_bambora_payform.py
> Fix randomly failing additional product order test

- resources/models.py
- resources/tests/test_resources_models.py
* Mark a berth as reserved when there's an offer for the berth either `DRAFTED` or `OFFERED`
* If the offer is accepted, the lease will be the one reserving the berth rather than the offer
* In any other case (rejected, cancelled, expired), the berth will be released
**[VEN-1282](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1282):** Sending an offer should reserve the berth
```shell
$ pytest resources/tests/test_resources_models.py::test_berth_is_available_inactive_offer
$ pytest resources/tests/test_resources_models.py::test_berth_is_not_available_active_offer
```
```python
from payments.tests.factories import BerthSwitchOfferFactory
from payments.enums import OfferStatus
offer = BerthSwitchOfferFactory(status=OfferStatus.DRAFTED)
from resources.models import Berth
assert not …
```
> VEN-1282 | Mark a berth as reserved when there's an open offer

- .github/workflows/review.yml
- applications/models.py
- berth_reservations/tests/conftest.py
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- payments/models.py
- payments/notifications/dummy_context.py
- payments/notifications/types.py
- payments/schema/mutations.py
- payments/schema/types.py
- payments/tests/test_payments_mutations_send_berth_switch_offer.py
- payments/utils.py
- scripts/load_notification_templates.py
- templates/email/messages/berth_offer_switch_en.html
- templates/email/messages/berth_offer_switch_fi.html
- templates/email/messages/berth_offer_switch_sv.html
- templates/sms/berth_switch_notice_en.txt
- templates/sms/berth_switch_notice_fi.txt
- templates/sms/berth_switch_notice_sv.txt
* SendBerthSwitchOfferMutation (naming changed to match CreateBerthSwitchOfferMutation - jira case had CreateSwitchOfferMutation
* Email and sms templates. New NotificationType for the SMS.
* Some code refactorings
**[VEN-1215](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1215):**
> VEN-1215: Mutation to send switch offer.

- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
Reverts City-of-Helsinki/berth-reservations#536
> Revert "VEN-1283: modify UpdateOrderMutation to allow multiple Orders at a time"

- templates/email/messages/berth_application_confirmation_fi.html
Fix also the Finnish template
**[VEN-1231](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1231):**
> VEN-1231: fix berth application confirmation in finnish

- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
This changes were already merged and tested but had to be reverted before the last release
#536 
#541
> VEN-1283 | Modify UpdateOrderMutation to allow multiple Orders

- payments/utils.py
fix additional_services in template context 
**[VEN-1309](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1309):**
> VEN-1309: fix invoice sending by email

- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
Reverts City-of-Helsinki/berth-reservations#549
> Revert "VEN-1283 | Modify UpdateOrderMutation to allow multiple Orders"

- payments/schema/mutations.py
- payments/tests/test_payments_mutations.py
> VEN-1283 | Pls let's stop this

- .prod/on_deploy.sh
- customers/exceptions.py
- customers/management/commands/create_customer_profile.py
- customers/services/profile.py
- leases/management/commands/import_winter_leases_from_csv.py
- resources/fixtures/helsinki-harbor-resources.json
* Add a command to create a profile (on Profiili and vene)
* Add the command to import the winter leases from the leases csv
**[VEN-877](https://helsinkisolutionoffice.atlassian.net/browse/VEN-877):** find a way to import marked WS data from latest Timmi data file and import it to production
1. Get the `profile-token` from the Admin UI
```js
JSON.parse(localStorage.apiTokens)["https://api.hel.fi/auth/helsinkiprofile"]
```
2. Download the attached CSV ([test_winter_invoices.csv](https://github.com/City-of-Helsinki/berth-reservations/files/6357930/test_winter_invoices.csv))
3. Call the create command
```shell
python manage.py import_winter_leases_from_csv \
--profile-token "" \
--lease-file-path "/path/to/test_winter_invoices.csv"
```
* The CSV should have the following format:
```
Section …
```
> VEN-877 | Import leases from leases csv

- payments/providers/bambora_payform.py
* Rename the product id field on Bambora payload
> VEN-1319 | Rename the product id field on Bambora payload

- customers/services/profile.py
- leases/management/commands/import_winter_leases_from_csv.py
* Parse properly the result of multiple profiles on `find_profile`
* Print the results to give some feedback when the command ends
> VEN-877 | Fix errors when importing winter leases

- .prod/on_deploy.sh
- applications/models.py
- users/management/commands/set_group_model_permissions.py
* Disable validation for application boat draught
**[VEN-1325](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1325):** Validation errors for application boat draught
> VEN-1325 | Disable validation for application boat draught

- applications/schema/types.py
small fixes to BerthSwitchType and HarborChoiceType
> VEN-1229: small fixes to BerthSwitchType and HarborChoiceType

- .prod/on_deploy.sh
> Disable temporarily the commands on deploy

- .prod/on_deploy.sh
Re-enable migrations
Reverts City-of-Helsinki/berth-reservations#576
> Revert "Disable temporarily the commands on deploy"

- payments/schema/queries.py
- payments/tests/conftest.py
- payments/tests/test_payments_queries.py
Fix error when retrieving OrderDetails for unmarked winter storage
Add tests for the bug.
**[VEN-1293](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1293):**
> VEN-1293 unmarked winter storage fix

- .github/workflows/review.yml
- .github/workflows/staging.yml
- .github/workflows/stop_review.yml
Jira: DEVOPS-256 and DEVOPS-318
> Aiven review DB and manual run

- .prod/on_deploy.sh
disable create_users_for_customers in .prod/on_deploy.sh
> disable create_users_for_customers in .prod/on_deploy.sh

- applications/schema/inputs.py
- applications/schema/mutations.py
- applications/tests/test_applications_mutations.py
* Refactor the `UpdateXXXApplicationMutation` mutations to support a customer updating the information on their own application
**[VEN-1219](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1219):** Mutation for the customer to update own applications
```shell
$ pytest applications/tests/test_applications_mutations.py
```
> VEN-1219 | Update own application

- applications/schema/mutations.py
- applications/tests/test_applications_mutations.py
* Add mutation to extend validity of berth applications
**[VEN-1223](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1223):** Mutation to keep the customer's application valid when no berth is offered
```shell
$ pytest applications/tests/test_applications_mutations.py::test_extend_berth_application
$ pytest applications/tests/test_applications_mutations.py::test_extend_berth_application_not_enough_permissions
$ pytest applications/tests/test_applications_mutations.py::test_extend_berth_application_not_rejected
```
> VEN-1223 | Add mutation to extend validity of berth applications

- payments/schema/queries.py
- payments/schema/types.py
- payments/tests/test_payments_queries.py
*  Add OfferDetailsType and offer_details query
**[VEN-1312](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1312):** Add OfferDetailsType
```shell
$ pytest payments/tests/test_payments_queries.py::test_get_offer_status
```
> VEN-1312 | Add OfferDetails

- leases/services/invoice/winter_storage.py
* Fix the date calculation for winter invoice service
> Fix the date calculation for winter invoice service

- leases/admin.py
* Add an action to generate contracts for leases from Django admin
* Add some `autocomplete_fields` to optimise the `Lease` pages
* Display the `order_number` from the `OrderInline` from the `Lease` pages
**Generate contract action for leases:**
**Autocomplete lease boat:**
**Order number on Order inline:**
> Django admin improvements

- resources/models.py
- resources/tests/test_resources_models.py
* Fix conditions for available winter places
**[VEN-1373](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1373):** Admin UI: Admin can't assing marked WS place when contract has been cancelled
```shell
$ pytest resources/tests/test_resources_models.py::test_winter_storage_place_is_available_when_customer_terminates_lease
```
> VEN-1373 | Fix available winter places

- leases/schema/mutations.py
- leases/tests/test_lease_mutations.py
Added `customerId` field to `CreateWinterStorageLeaseMutation` for providing the customer when a winter storage lease is created without an application. A place is mandatory in such leases.
**[VEN-1372](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1372): Create marked WS lease without application** 
The implementation is based on the corresponding implementation of berth leases without an application.
> VEN-1372 | Allow creating winter storage lease without application

- payments/providers/talpa_ecom.py
- payments/tests/test_talpa_ecom.py
* Force some lazy strings
* Fix price calculations for totals
> VEN-1411 | Fix more wrong payload fields

- payments/providers/talpa_ecom.py
- payments/tests/test_talpa_ecom.py
* Fix parsing of notify request body
> VEN-1411 | Fix notify-request body parse

- customers/schema/queries.py
- customers/tests/test_customers_queries.py
- customers/utils.py
**[VEN-1440](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1440):**
> VEN-1440 Add customer profile filters to GraphQL query

- customers/schema/queries.py
- customers/tests/test_customers_queries.py
- payments/tests/test_talpa_ecom.py
VEN-1469. Fixing the issue with in_bulk implementation by changing it to case-when-preserved order-by -query
> Using Case-When to order the customers by profile query set

- customers/services/profile.py
> Added a timeout to find profile query

- customers/schema/queries.py
- customers/services/profile.py
> Added first and last filters to find profile -query

- customers/schema/queries.py
- customers/services/profile.py
> Recursively fetch all the ids from profile

- customers/schema/queries.py
- customers/services/profile.py
VEN-1469. Trying to fix performance issues.
> Added ids_only attribute to find_profiles query

- customers/schema/queries.py
VEN-1469. Instead of summing berth leases and winter storages together, check whether or not there are multiple of one of them.
"Enemmän kuin yksi vene- tai talvisäilytyspaikka"
> Fix to berthProfiles berth leases filter

- customers/schema/queries.py
- customers/tests/test_customers_queries.py
- customers/utils.py
> Removed the filter trigger parameters from berthProfiles query

- customers/schema/queries.py
- customers/services/profile.py
- customers/tests/test_customers_queries.py
- customers/utils.py
VEN-1469. Filter first by berth filters, then by profile filters and then return the berth query in the right order.
> Find profile filters first by berth data and then by profile data

- applications/tests/conftest.py
- customers/tests/test_customers_queries.py
- exports/tests/test_berth_application_export.py
- exports/tests/test_customer_export.py
- exports/tests/test_unmarked_winter_storage_application_export.py
- exports/tests/test_winter_storage_application_export.py
- exports/views.py
- exports/xlsx_writer.py
This PR adds query optimizations for the excel exports.
> VEN-1434 | Optimize excel export queries

- leases/models.py
- leases/utils.py
- resources/schema/types.py
- resources/tests/test_resources_queries.py
> Add previous season lease resolver to the berths node

- berth_reservations/middlewares.py
- leases/schema/types.py
- leases/tests/test_lease_queries.py
- payments/schema/loaders.py
- resources/schema/types.py
- resources/tests/test_resources_queries.py
> Add the current berth switch offer's customer details to BerthLeaseNode

- customers/enums.py
- customers/tests/test_customers_queries.py
> Remove the digital invoice -invoicing type

- berth_reservations/tests/conftest.py
- customers/tests/conftest.py
- customers/tests/test_sms_notification_service.py
- payments/notifications/dummy_context.py
- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/tests/test_payments_mutations_approve_order.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/utils.py
- templates/sms/invoice_notice_en.txt
- templates/sms/invoice_notice_fi.txt
- templates/sms/invoice_notice_sv.txt
Add information about the berth to the new berth order SMS
**[VEN-1462](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1462):** Addition to SMS berth offer notification
> VEN-1462 | Add information about the berth to the new berth order SMS

- payments/tests/test_payments_reminder_notifications.py
> Test payment reminder for different order statuses

- .github/workflows/review.yml
- docker-entrypoint.sh
Review deployment fails
**[DEVOPS-390](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-390):**
> Review action fails

- .github/workflows/load_tests.yml
- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
- k6LoadTests.js
Horizontal pod autoscaler [DEVOPS-436](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-436)
Load tests [DEVOPS-428](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-428])
Prevent parallel deployment [DEVOPS-429](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-429])
> Horizontal pod autoscaler

- Dockerfile
- docker/postgres/Dockerfile
Add group 0 write access for generated emails DEVOPS-481
Postgre/postgis Dockerfile is modified for Openshift
[DEVOPS-481]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Openshift deployment fixes

- k6LoadTests.js
[DEVOPS-481](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-481)
[DEVOPS-481]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> k6 loadtests url to Platta

- requirements.in
- requirements.txt
> Fix to use django-munigeo from original repo, not from forked repo

- Dockerfile
> Writable app data

- resources/management/commands/assign_area_regions.py
> FIX NoneType handling in assign_area_regions management command

- resources/management/commands/assign_area_regions.py
> UPDATE hardcoded list to determine area regions

- resources/management/commands/assign_area_regions.py
> FIX code style error

- resources/management/commands/assign_area_regions.py
> FIX flake8 validation

- customers/tests/test_gdpr_api.py
> REMOVE configuration overrides from GDPR API tests

- customers/tests/test_gdpr_api.py
> Fix code style

- customers/schema/queries.py
> FIX set recursively fetch all in profile queries to false

- customers/schema/queries.py
- customers/services/profile.py
> ADD retries to profile query

- customers/services/profile.py
> FIX remove unused imports

- leases/tests/test_lease_sticker_mutations.py
- leases/tests/test_send_berth_invoice_service.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/tests/test_payments_mutations_send_berth_switch_offer.py
> FIX temporarily disable tests

- .prod/uwsgi.ini
> FIX increase UWSGI timeout

- .prod/uwsgi.ini
> FIX increase UWSGI http-timeout

- customers/services/profile.py
> FIX reduce profile fetch batch size

- customers/tests/test_customers_mutations.py
- customers/tests/test_customers_queries.py
- customers/tests/test_profile_service.py
- leases/tests/test_lease_mutations.py
- leases/tests/test_lease_sticker_mutations.py
- leases/tests/test_send_berth_invoice_service.py
- payments/tests/test_payments_mutations_approve_ap_order.py
- payments/tests/test_payments_mutations_approve_order.py
- payments/tests/test_payments_mutations_create_berth_switch_offer.py
- payments/tests/test_payments_mutations_resend_order.py
- payments/tests/test_payments_mutations_send_berth_switch_offer.py
> FIX fix and enable tests with profile queries

- Dockerfile
- scripts/load_notification_templates.py
> Process deleting in a transaction

- payments/providers/talpa_ecom.py
refs VEN-1575
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
> VEN-1575 | fix: tax_percentage use in TalpaEComProvider.payload_add_to_items
